version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./database_scripts:/docker-entrypoint-initdb.d

  api:  
    build:
      context: .  
      dockerfile: Dockerfile  
    container_name: employees-app
    ports:
      - "80:80"  
    environment:
      - API_KEY=${API_KEY}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING} 
    depends_on:
      - postgres 