INSERT INTO business_type (name)
VALUES
    ('Alimentos y Bebidas'),
    ('Arte y Cultura'),
    ('Automotriz'),
    ('Belleza y Cuidado Personal'),
    ('Comercio Minorista'),
    ('Construcción y Mantenimiento'),
    ('Deportes y Aire Libre'),
    ('Educación'),
    ('Electrónica'),
    ('Entretenimiento'),
    ('Finanzas y Banca'),
    ('Hogar y Jardín'),
    ('Medios y Comunicación'),
    ('Moda y Ropa'),
    ('Mascotas'),
    ('Restaurante'),
    ('Salud y Cuidado'),
    ('Servicios Profesionales'),
    ('Tecnología'),
    ('Transporte'),
    ('Turismo'),
    ('Vehículos'),
    ('Viajes'),
    ('Vivienda'),
    ('Otros');