INSERT INTO municipality(state_id, name) VALUES
('AGU', 'Aguascalientes'),
('BCN', 'Ensenada'),
('BCS', 'Comondú'),
('CAM', 'Calkiní'),
('COA', 'Abasolo'),
('COL', 'Armería'),
('CHH', 'Ahumada'),
('CHP', 'Acacoyagua'),
('DUR', 'Canatlán'),
('GRO', 'Acapulco de Juárez'),
('GUA', 'Abasolo'),
('HID', 'Acatlán'),
('JAL', 'Acatic'),
('MEX', 'Acambay de Ruíz Castañeda'),
('MIC', 'Acuitzio'),
('MOR', 'Amacuzac'),
('NAY', 'Acaponeta'),
('NLE', 'Abasolo'),
('OAX', 'Abejones'),
('PUE', 'Acajete'),
('QUE', 'Amealco de Bonfil'),
('ROO', 'Cozumel'),
('SIN', 'Ahome'),
('SLP', 'Ahualulco'),
('SON', 'Aconchi'),
('TAB', 'Balancán'),
('TAM', 'Abasolo'),
('TLA', 'Amaxac de Guerrero'),
('VER', 'Acajete'),
('YUC', 'Abalá'),
('ZAC', 'Apozol'),
('AGU', 'Asientos'),
('BCN', 'Mexicali'),
('BCS', 'Mulegé'),
('CAM', 'Campeche'),
('COA', 'Acuña'),
('COL', 'Colima'),
('CHH', 'Aldama'),
('CHP', 'Acala'),
('CMX', 'Azcapotzalco'),
('DUR', 'Canelas'),
('GRO', 'Ahuacuotzingo'),
('GUA', 'Acámbaro'),
('HID', 'Acaxochitlán'),
('JAL', 'Acatlán de Juárez'),
('MEX', 'Acolman'),
('MIC', 'Aguililla'),
('MOR', 'Atlatlahucan'),
('NAY', 'Ahuacatlán'),
('NLE', 'Agualeguas'),
('OAX', 'Acatlán de Pérez Figueroa'),
('PUE', 'Acateno'),
('QUE', 'Pinal de Amoles'),
('ROO', 'Felipe Carrillo Puerto'),
('SIN', 'Angostura'),
('SLP', 'Alaquines'),
('SON', 'Agua Prieta'),
('TAB', 'Cárdenas'),
('TAM', 'Aldama'),
('TLA', 'Apetatitlán de Antonio Carvajal'),
('VER', 'Acatlán'),
('YUC', 'Acanceh'),
('ZAC', 'Apulco'),
('AGU', 'Calvillo'),
('BCN', 'Tecate'),
('BCS', 'La Paz'),
('CAM', 'Carmen'),
('COA', 'Allende'),
('COL', 'Comala'),
('CHH', 'Allende'),
('CHP', 'Acapetahua'),
('CMX', 'Coyoacán'),
('DUR', 'Coneto de Comonfort'),
('GRO', 'Ajuchitlán del Progreso'),
('GUA', 'San Miguel de Allende'),
('HID', 'Actopan'),
('JAL', 'Ahualulco de Mercado'),
('MEX', 'Aculco'),
('MIC', 'Álvaro Obregón'),
('MOR', 'Axochiapan'),
('NAY', 'Amatlán de Cañas'),
('NLE', 'Los Aldamas'),
('OAX', 'Asunción Cacalotepec'),
('PUE', 'Acatlán'),
('QUE', 'Arroyo Seco'),
('ROO', 'Isla Mujeres'),
('SIN', 'Badiraguato'),
('SLP', 'Aquismón'),
('SON', 'Alamos'),
('TAB', 'Centla'),
('TAM', 'Altamira'),
('TLA', 'Atlangatepec'),
('VER', 'Acayucan'),
('YUC', 'Akil'),
('ZAC', 'Atolinga'),
('AGU', 'Cosío'),
('BCN', 'Tijuana'),
('CAM', 'Champotón'),
('COA', 'Arteaga'),
('COL', 'Coquimatlán'),
('CHH', 'Aquiles Serdán'),
('CHP', 'Altamirano'),
('CMX', 'Cuajimalpa de Morelos'),
('DUR', 'Cuencamé'),
('GRO', 'Alcozauca de Guerrero'),
('GUA', 'Apaseo el Alto'),
('HID', 'Agua Blanca de Iturbide'),
('JAL', 'Amacueca'),
('MEX', 'Almoloya de Alquisiras'),
('MIC', 'Angamacutiro'),
('MOR', 'Ayala'),
('NAY', 'Compostela'),
('NLE', 'Allende'),
('OAX', 'Asunción Cuyotepeji'),
('PUE', 'Acatzingo'),
('QUE', 'Cadereyta de Montes'),
('ROO', 'Othón P. Blanco'),
('SIN', 'Concordia'),
('SLP', 'Armadillo de los Infante'),
('SON', 'Altar'),
('TAB', 'Centro'),
('TAM', 'Antiguo Morelos'),
('TLA', 'Atltzayanca'),
('VER', 'Actopan'),
('YUC', 'Baca'),
('ZAC', 'Benito Juárez'),
('AGU', 'Jesús María'),
('BCN', 'Playas de Rosarito'),
('CAM', 'Hecelchakán'),
('COA', 'Candela'),
('COL', 'Cuauhtémoc'),
('CHH', 'Ascensión'),
('CHP', 'Amatán'),
('CMX', 'Gustavo A. Madero'),
('DUR', 'Durango'),
('GRO', 'Alpoyeca'),
('GUA', 'Apaseo el Grande'),
('HID', 'Ajacuba'),
('JAL', 'Amatitán'),
('MEX', 'Almoloya de Juárez'),
('MIC', 'Angangueo'),
('MOR', 'Coatlán del Río'),
('NAY', 'Huajicori'),
('NLE', 'Anáhuac'),
('OAX', 'Asunción Ixtaltepec'),
('PUE', 'Acteopan'),
('QUE', 'Colón'),
('ROO', 'Benito Juárez'),
('SIN', 'Cosalá'),
('SLP', 'Cárdenas'),
('SON', 'Arivechi'),
('TAB', 'Comalcalco'),
('TAM', 'Burgos'),
('TLA', 'Apizaco'),
('VER', 'Acula'),
('YUC', 'Bokobá'),
('ZAC', 'Calera'),
('AGU', 'Pabellón de Arteaga'),
('CAM', 'Hopelchén'),
('COA', 'Castaños'),
('COL', 'Ixtlahuacán'),
('CHH', 'Bachíniva'),
('CHP', 'Amatenango de la Frontera'),
('CMX', 'Iztacalco'),
('DUR', 'General Simón Bolívar'),
('GRO', 'Apaxtla'),
('GUA', 'Atarjea'),
('HID', 'Alfajayucan'),
('JAL', 'Ameca'),
('MEX', 'Almoloya del Río'),
('MIC', 'Apatzingán'),
('MOR', 'Cuautla'),
('NAY', 'Ixtlán del Río'),
('NLE', 'Apodaca'),
('OAX', 'Asunción Nochixtlán'),
('PUE', 'Ahuacatlán'),
('QUE', 'Corregidora'),
('ROO', 'José María Morelos'),
('SIN', 'Culiacán'),
('SLP', 'Catorce'),
('SON', 'Arizpe'),
('TAB', 'Cunduacán'),
('TAM', 'Bustamante'),
('TLA', 'Calpulalpan'),
('VER', 'Acultzingo'),
('YUC', 'Buctzotz'),
('ZAC', 'Cañitas de Felipe Pescador'),
('AGU', 'Rincón de Romos'),
('CAM', 'Palizada'),
('COA', 'Cuatro Ciénegas'),
('COL', 'Manzanillo'),
('CHH', 'Balleza'),
('CHP', 'Amatenango del Valle'),
('CMX', 'Iztapalapa'),
('DUR', 'Gómez Palacio'),
('GRO', 'Arcelia'),
('GUA', 'Celaya'),
('HID', 'Almoloya'),
('JAL', 'San Juanito de Escobedo'),
('MEX', 'Amanalco'),
('MIC', 'Aporo'),
('MOR', 'Cuernavaca'),
('NAY', 'Jala'),
('NLE', 'Aramberri'),
('OAX', 'Asunción Ocotlán'),
('PUE', 'Ahuatlán'),
('QUE', 'Ezequiel Montes'),
('ROO', 'Lázaro Cárdenas'),
('SIN', 'Choix'),
('SLP', 'Cedral'),
('SON', 'Atil'),
('TAB', 'Emiliano Zapata'),
('TAM', 'Camargo'),
('TLA', 'El Carmen Tequexquitla'),
('VER', 'Camarón de Tejeda'),
('YUC', 'Cacalchén'),
('ZAC', 'Concepción del Oro'),
('AGU', 'San José de Gracia'),
('BCS', 'Los Cabos'),
('CAM', 'Tenabo'),
('COA', 'Escobedo'),
('COL', 'Minatitlán'),
('CHH', 'Batopilas'),
('CHP', 'Angel Albino Corzo'),
('CMX', 'La Magdalena Contreras'),
('DUR', 'Guadalupe Victoria'),
('GRO', 'Atenango del Río'),
('GUA', 'Manuel Doblado'),
('HID', 'Apan'),
('JAL', 'Arandas'),
('MEX', 'Amatepec'),
('MIC', 'Aquila'),
('MOR', 'Emiliano Zapata'),
('NAY', 'Xalisco'),
('NLE', 'Bustamante'),
('OAX', 'Asunción Tlacolulita'),
('PUE', 'Ahuazotepec'),
('QUE', 'Huimilpan'),
('ROO', 'Solidaridad'),
('SIN', 'Elota'),
('SLP', 'Cerritos'),
('SON', 'Bacadéhuachi'),
('TAB', 'Huimanguillo'),
('TAM', 'Casas'),
('TLA', 'Cuapiaxtla'),
('VER', 'Alpatláhuac'),
('YUC', 'Calotmul'),
('ZAC', 'Cuauhtémoc'),
('AGU', 'Tepezalá'),
('BCS', 'Loreto'),
('CAM', 'Escárcega'),
('COA', 'Francisco I. Madero'),
('COL', 'Tecomán'),
('CHH', 'Bocoyna'),
('CHP', 'Arriaga'),
('CMX', 'Milpa Alta'),
('DUR', 'Guanaceví'),
('GRO', 'Atlamajalcingo del Monte'),
('GUA', 'Comonfort'),
('HID', 'El Arenal'),
('JAL', 'El Arenal'),
('MEX', 'Amecameca'),
('MIC', 'Ario'),
('MOR', 'Huitzilac'),
('NAY', 'Del Nayar'),
('NLE', 'Cadereyta Jiménez'),
('OAX', 'Ayotzintepec'),
('PUE', 'Ahuehuetitla'),
('QUE', 'Jalpan de Serra'),
('ROO', 'Tulum'),
('SIN', 'Escuinapa'),
('SLP', 'Cerro de San Pedro'),
('SON', 'Bacanora'),
('TAB', 'Jalapa'),
('TAM', 'Ciudad Madero'),
('TLA', 'Cuaxomulco'),
('VER', 'Alto Lucero de Gutiérrez Barrios'),
('YUC', 'Cansahcab'),
('ZAC', 'Chalchihuites'),
('AGU', 'El Llano'),
('CAM', 'Calakmul'),
('COA', 'Frontera'),
('COL', 'Villa de Álvarez'),
('CHH', 'Buenaventura'),
('CHP', 'Bejucal de Ocampo'),
('CMX', 'Álvaro Obregón'),
('DUR', 'Hidalgo'),
('GRO', 'Atlixtac'),
('GUA', 'Coroneo'),
('HID', 'Atitalaquia'),
('JAL', 'Atemajac de Brizuela'),
('MEX', 'Apaxco'),
('MIC', 'Arteaga'),
('MOR', 'Jantetelco'),
('NAY', 'Rosamorada'),
('NLE', 'El Carmen'),
('OAX', 'El Barrio de la Soledad'),
('PUE', 'Ajalpan'),
('QUE', 'Landa de Matamoros'),
('ROO', 'Bacalar'),
('SIN', 'El Fuerte'),
('SLP', 'Ciudad del Maíz'),
('SON', 'Bacerac'),
('TAB', 'Jalpa de Méndez'),
('TAM', 'Cruillas'),
('TLA', 'Chiautempan'),
('VER', 'Altotonga'),
('YUC', 'Cantamayec'),
('ZAC', 'Fresnillo'),
('AGU', 'San Francisco de los Romo'),
('CAM', 'Candelaria'),
('COA', 'General Cepeda'),
('CHH', 'Camargo'),
('CHP', 'Bella Vista'),
('CMX', 'Tláhuac'),
('DUR', 'Indé'),
('GRO', 'Atoyac de Álvarez'),
('GUA', 'Cortazar'),
('HID', 'Atlapexco'),
('JAL', 'Atengo'),
('MEX', 'Atenco'),
('MIC', 'Briseñas'),
('MOR', 'Jiutepec'),
('NAY', 'Ruíz'),
('NLE', 'Cerralvo'),
('OAX', 'Calihualá'),
('PUE', 'Albino Zertuche'),
('QUE', 'El Marqués'),
('ROO', 'Puerto Morelos'),
('SIN', 'Guasave'),
('SLP', 'Ciudad Fernández'),
('SON', 'Bacoachi'),
('TAB', 'Jonuta'),
('TAM', 'Gómez Farías'),
('TLA', 'Muñoz de Domingo Arenas'),
('VER', 'Alvarado'),
('YUC', 'Celestún'),
('ZAC', 'Trinidad García de la Cadena'),
('COA', 'Guerrero'),
('CHH', 'Carichí'),
('CHP', 'Berriozábal'),
('CMX', 'Tlalpan'),
('DUR', 'Lerdo'),
('GRO', 'Ayutla de los Libres'),
('GUA', 'Cuerámaro'),
('HID', 'Atotonilco el Grande'),
('JAL', 'Atenguillo'),
('MEX', 'Atizapán'),
('MIC', 'Buenavista'),
('MOR', 'Jojutla'),
('NAY', 'San Blas'),
('NLE', 'Ciénega de Flores'),
('OAX', 'Candelaria Loxicha'),
('PUE', 'Aljojuca'),
('QUE', 'Pedro Escobedo'),
('SIN', 'Mazatlán'),
('SLP', 'Tancanhuitz'),
('SON', 'Bácum'),
('TAB', 'Macuspana'),
('TAM', 'González'),
('TLA', 'Españita'),
('VER', 'Amatitlán'),
('YUC', 'Cenotillo'),
('ZAC', 'Genaro Codina'),
('COA', 'Hidalgo'),
('CHH', 'Casas Grandes'),
('CHP', 'Bochil'),
('CMX', 'Xochimilco'),
('DUR', 'Mapimí'),
('GRO', 'Azoyú'),
('GUA', 'Doctor Mora'),
('HID', 'Atotonilco de Tula'),
('JAL', 'Atotonilco el Alto'),
('MEX', 'Atizapán de Zaragoza'),
('MIC', 'Carácuaro'),
('MOR', 'Jonacatepec'),
('NAY', 'San Pedro Lagunillas'),
('NLE', 'China'),
('OAX', 'Ciénega de Zimatlán'),
('PUE', 'Altepexi'),
('QUE', 'Peñamiller'),
('SIN', 'Mocorito'),
('SLP', 'Ciudad Valles'),
('SON', 'Banámichi'),
('TAB', 'Nacajuca'),
('TAM', 'Güémez'),
('TLA', 'Huamantla'),
('VER', 'Naranjos Amatlán'),
('YUC', 'Conkal'),
('ZAC', 'General Enrique Estrada'),
('COA', 'Jiménez'),
('CHH', 'Coronado'),
('CHP', 'El Bosque'),
('CMX', 'Benito Juárez'),
('DUR', 'Mezquital'),
('GRO', 'Benito Juárez'),
('GUA', 'Dolores Hidalgo Cuna de la Independencia Nacional'),
('HID', 'Calnali'),
('JAL', 'Atoyac'),
('MEX', 'Atlacomulco'),
('MIC', 'Coahuayana'),
('MOR', 'Mazatepec'),
('NAY', 'Santa María del Oro'),
('NLE', 'Doctor Arroyo'),
('OAX', 'Ciudad Ixtepec'),
('PUE', 'Amixtlán'),
('QUE', 'Querétaro'),
('SIN', 'Rosario'),
('SLP', 'Coxcatlán'),
('SON', 'Baviácora'),
('TAB', 'Paraíso'),
('TAM', 'Guerrero'),
('TLA', 'Hueyotlipan'),
('VER', 'Amatlán de los Reyes'),
('YUC', 'Cuncunul'),
('ZAC', 'General Francisco R. Murguía'),
('COA', 'Juárez'),
('CHH', 'Coyame del Sotol'),
('CHP', 'Cacahoatán'),
('CMX', 'Cuauhtémoc'),
('DUR', 'Nazas'),
('GRO', 'Buenavista de Cuéllar'),
('GUA', 'Guanajuato'),
('HID', 'Cardonal'),
('JAL', 'Autlán de Navarro'),
('MEX', 'Atlautla'),
('MIC', 'Coalcomán de Vázquez Pallares'),
('MOR', 'Miacatlán'),
('NAY', 'Santiago Ixcuintla'),
('NLE', 'Doctor Coss'),
('OAX', 'Coatecas Altas'),
('PUE', 'Amozoc'),
('QUE', 'San Joaquín'),
('SIN', 'Salvador Alvarado'),
('SLP', 'Charcas'),
('SON', 'Bavispe'),
('TAB', 'Tacotalpa'),
('TAM', 'Gustavo Díaz Ordaz'),
('TLA', 'Ixtacuixtla de Mariano Matamoros'),
('VER', 'Angel R. Cabada'),
('YUC', 'Cuzamá'),
('ZAC', 'El Plateado de Joaquín Amaro'),
('COA', 'Lamadrid'),
('CHH', 'La Cruz'),
('CHP', 'Catazajá'),
('CMX', 'Miguel Hidalgo'),
('DUR', 'Nombre de Dios'),
('GRO', 'Coahuayutla de José María Izazaga'),
('GUA', 'Huanímaro'),
('HID', 'Cuautepec de Hinojosa'),
('JAL', 'Ayotlán'),
('MEX', 'Axapusco'),
('MIC', 'Coeneo'),
('MOR', 'Ocuituco'),
('NAY', 'Tecuala'),
('NLE', 'Doctor González'),
('OAX', 'Coicoyán de las Flores'),
('PUE', 'Aquixtla'),
('QUE', 'San Juan del Río'),
('SIN', 'San Ignacio'),
('SLP', 'Ebano'),
('SON', 'Benjamín Hill'),
('TAB', 'Teapa'),
('TAM', 'Hidalgo'),
('TLA', 'Ixtenco'),
('VER', 'La Antigua'),
('YUC', 'Chacsinkín'),
('ZAC', 'General Pánfilo Natera'),
('COA', 'Matamoros'),
('CHH', 'Cuauhtémoc'),
('CHP', 'Cintalapa'),
('CMX', 'Venustiano Carranza'),
('DUR', 'Ocampo'),
('GRO', 'Cocula'),
('GUA', 'Irapuato'),
('HID', 'Chapantongo'),
('JAL', 'Ayutla'),
('MEX', 'Ayapango'),
('MIC', 'Contepec'),
('MOR', 'Puente de Ixtla'),
('NAY', 'Tepic'),
('NLE', 'Galeana'),
('OAX', 'La Compañía'),
('PUE', 'Atempan'),
('QUE', 'Tequisquiapan'),
('SIN', 'Sinaloa'),
('SLP', 'Guadalcázar'),
('SON', 'Caborca'),
('TAB', 'Tenosique'),
('TAM', 'Jaumave'),
('TLA', 'Mazatecochco de José María Morelos'),
('VER', 'Apazapan'),
('YUC', 'Chankom'),
('ZAC', 'Guadalupe'),
('COA', 'Monclova'),
('CHH', 'Cusihuiriachi'),
('CHP', 'Coapilla'),
('DUR', 'El Oro'),
('GRO', 'Copala'),
('GUA', 'Jaral del Progreso'),
('HID', 'Chapulhuacán'),
('JAL', 'La Barca'),
('MEX', 'Calimaya'),
('MIC', 'Copándaro'),
('MOR', 'Temixco'),
('NAY', 'Tuxpan'),
('NLE', 'García'),
('OAX', 'Concepción Buenavista'),
('PUE', 'Atexcal'),
('QUE', 'Tolimán'),
('SIN', 'Navolato'),
('SLP', 'Huehuetlán'),
('SON', 'Cajeme'),
('TAM', 'Jiménez'),
('TLA', 'Contla de Juan Cuamatzi'),
('VER', 'Aquila'),
('YUC', 'Chapab'),
('ZAC', 'Huanusco'),
('COA', 'Morelos'),
('CHH', 'Chihuahua'),
('CHP', 'Comitán de Domínguez'),
('DUR', 'Otáez'),
('GRO', 'Copalillo'),
('GUA', 'Jerécuaro'),
('HID', 'Chilcuautla'),
('JAL', 'Bolaños'),
('MEX', 'Capulhuac'),
('MIC', 'Cotija'),
('MOR', 'Tepalcingo'),
('NAY', 'La Yesca'),
('NLE', 'San Pedro Garza García'),
('OAX', 'Concepción Pápalo'),
('PUE', 'Atlixco'),
('SLP', 'Lagunillas'),
('SON', 'Cananea'),
('TAM', 'Llera'),
('TLA', 'Tepetitla de Lardizábal'),
('VER', 'Astacinga'),
('YUC', 'Chemax'),
('ZAC', 'Jalpa'),
('COA', 'Múzquiz'),
('CHH', 'Chínipas'),
('CHP', 'La Concordia'),
('DUR', 'Pánuco de Coronado'),
('GRO', 'Copanatoyac'),
('GUA', 'León'),
('HID', 'Eloxochitlán'),
('JAL', 'Cabo Corrientes'),
('MEX', 'Coacalco de Berriozábal'),
('MIC', 'Cuitzeo'),
('MOR', 'Tepoztlán'),
('NAY', 'Bahía de Banderas'),
('NLE', 'General Bravo'),
('OAX', 'Constancia del Rosario'),
('PUE', 'Atoyatempan'),
('SLP', 'Matehuala'),
('SON', 'Carbó'),
('TAM', 'Mainero'),
('TLA', 'Sanctórum de Lázaro Cárdenas'),
('VER', 'Atlahuilco'),
('YUC', 'Chicxulub Pueblo'),
('ZAC', 'Jerez'),
('COA', 'Nadadores'),
('CHH', 'Delicias'),
('CHP', 'Copainalá'),
('DUR', 'Peñón Blanco'),
('GRO', 'Coyuca de Benítez'),
('GUA', 'Moroleón'),
('HID', 'Emiliano Zapata'),
('JAL', 'Casimiro Castillo'),
('MEX', 'Coatepec Harinas'),
('MIC', 'Charapan'),
('MOR', 'Tetecala'),
('NLE', 'General Escobedo'),
('OAX', 'Cosolapa'),
('PUE', 'Atzala'),
('SLP', 'Mexquitic de Carmona'),
('SON', 'La Colorada'),
('TAM', 'El Mante'),
('TLA', 'Nanacamilpa de Mariano Arista'),
('VER', 'Atoyac'),
('YUC', 'Chichimilá'),
('ZAC', 'Jiménez del Teul'),
('COA', 'Nava'),
('CHH', 'Dr. Belisario Domínguez'),
('CHP', 'Chalchihuitán'),
('DUR', 'Poanas'),
('GRO', 'Coyuca de Catalán'),
('GUA', 'Ocampo'),
('HID', 'Epazoyucan'),
('JAL', 'Cihuatlán'),
('MEX', 'Cocotitlán'),
('MIC', 'Charo'),
('MOR', 'Tetela del Volcán'),
('NLE', 'General Terán'),
('OAX', 'Cosoltepec'),
('PUE', 'Atzitzihuacán'),
('SLP', 'Moctezuma'),
('SON', 'Cucurpe'),
('TAM', 'Matamoros'),
('TLA', 'Acuamanala de Miguel Hidalgo'),
('VER', 'Atzacan'),
('YUC', 'Chikindzonot'),
('ZAC', 'Juan Aldama'),
('COA', 'Ocampo'),
('CHH', 'Galeana'),
('CHP', 'Chamula'),
('DUR', 'Pueblo Nuevo'),
('GRO', 'Cuajinicuilapa'),
('GUA', 'Pénjamo'),
('HID', 'Francisco I. Madero'),
('JAL', 'Zapotlán el Grande'),
('MEX', 'Coyotepec'),
('MIC', 'Chavinda'),
('MOR', 'Tlalnepantla'),
('NLE', 'General Treviño'),
('OAX', 'Cuilápam de Guerrero'),
('PUE', 'Atzitzintla'),
('SLP', 'Rayón'),
('SON', 'Cumpas'),
('TAM', 'Méndez'),
('TLA', 'Natívitas'),
('VER', 'Atzalan'),
('YUC', 'Chocholá'),
('ZAC', 'Juchipila'),
('COA', 'Parras'),
('CHH', 'Santa Isabel'),
('CHP', 'Chanal'),
('DUR', 'Rodeo'),
('GRO', 'Cualác'),
('GUA', 'Pueblo Nuevo'),
('HID', 'Huasca de Ocampo'),
('JAL', 'Cocula'),
('MEX', 'Cuautitlán'),
('MIC', 'Cherán'),
('MOR', 'Tlaltizapán de Zapata'),
('NLE', 'General Zaragoza'),
('OAX', 'Cuyamecalco Villa de Zaragoza'),
('PUE', 'Axutla'),
('SLP', 'Rioverde'),
('SON', 'Divisaderos'),
('TAM', 'Mier'),
('TLA', 'Panotla'),
('VER', 'Tlaltetela'),
('YUC', 'Chumayel'),
('ZAC', 'Loreto'),
('COA', 'Piedras Negras'),
('CHH', 'Gómez Farías'),
('CHP', 'Chapultenango'),
('DUR', 'San Bernardo'),
('GRO', 'Cuautepec'),
('GUA', 'Purísima del Rincón'),
('HID', 'Huautla'),
('JAL', 'Colotlán'),
('MEX', 'Chalco'),
('MIC', 'Chilchota'),
('MOR', 'Tlaquiltenango'),
('NLE', 'General Zuazua'),
('OAX', 'Chahuites'),
('PUE', 'Ayotoxco de Guerrero'),
('SLP', 'Salinas'),
('SON', 'Empalme'),
('TAM', 'Miguel Alemán'),
('TLA', 'San Pablo del Monte'),
('VER', 'Ayahualulco'),
('YUC', 'Dzán'),
('ZAC', 'Luis Moya'),
('COA', 'Progreso'),
('CHH', 'Gran Morelos'),
('CHP', 'Chenalhó'),
('DUR', 'San Dimas'),
('GRO', 'Cuetzala del Progreso'),
('GUA', 'Romita'),
('HID', 'Huazalingo'),
('JAL', 'Concepción de Buenos Aires'),
('MEX', 'Chapa de Mota'),
('MIC', 'Chinicuila'),
('MOR', 'Tlayacapan'),
('NLE', 'Guadalupe'),
('OAX', 'Chalcatongo de Hidalgo'),
('PUE', 'Calpan'),
('SLP', 'San Antonio'),
('SON', 'Etchojoa'),
('TAM', 'Miquihuana'),
('TLA', 'Santa Cruz Tlaxcala'),
('VER', 'Banderilla'),
('YUC', 'Dzemul'),
('ZAC', 'Mazapil'),
('COA', 'Ramos Arizpe'),
('CHH', 'Guachochi'),
('CHP', 'Chiapa de Corzo'),
('DUR', 'San Juan de Guadalupe'),
('GRO', 'Cutzamala de Pinzón'),
('GUA', 'Salamanca'),
('HID', 'Huehuetla'),
('JAL', 'Cuautitlán de García Barragán'),
('MEX', 'Chapultepec'),
('MIC', 'Chucándiro'),
('MOR', 'Totolapan'),
('NLE', 'Los Herreras'),
('OAX', 'Chiquihuitlán de Benito Juárez'),
('PUE', 'Caltepec'),
('SLP', 'San Ciro de Acosta'),
('SON', 'Fronteras'),
('TAM', 'Nuevo Laredo'),
('TLA', 'Tenancingo'),
('VER', 'Benito Juárez'),
('YUC', 'Dzidzantún'),
('ZAC', 'Melchor Ocampo'),
('COA', 'Sabinas'),
('CHH', 'Guadalupe'),
('CHP', 'Chiapilla'),
('DUR', 'San Juan del Río'),
('GRO', 'Chilapa de Álvarez'),
('GUA', 'Salvatierra'),
('HID', 'Huejutla de Reyes'),
('JAL', 'Cuautla'),
('MEX', 'Chiautla'),
('MIC', 'Churintzio'),
('MOR', 'Xochitepec'),
('NLE', 'Higueras'),
('OAX', 'Heroica Ciudad de Ejutla de Crespo'),
('PUE', 'Camocuautla'),
('SLP', 'San Luis Potosí'),
('SON', 'Granados'),
('TAM', 'Nuevo Morelos'),
('TLA', 'Teolocholco'),
('VER', 'Boca del Río'),
('YUC', 'Dzilam de Bravo'),
('ZAC', 'Mezquital del Oro'),
('COA', 'Sacramento'),
('CHH', 'Guadalupe y Calvo'),
('CHP', 'Chicoasén'),
('DUR', 'San Luis del Cordero'),
('GRO', 'Chilpancingo de los Bravo'),
('GUA', 'San Diego de la Unión'),
('HID', 'Huichapan'),
('JAL', 'Cuquío'),
('MEX', 'Chicoloapan'),
('MIC', 'Churumuco'),
('MOR', 'Yautepec'),
('NLE', 'Hualahuises'),
('OAX', 'Eloxochitlán de Flores Magón'),
('PUE', 'Caxhuacan'),
('SLP', 'San Martín Chalchicuautla'),
('SON', 'Guaymas'),
('TAM', 'Ocampo'),
('TLA', 'Tepeyanco'),
('VER', 'Calcahualco'),
('YUC', 'Dzilam González'),
('ZAC', 'Miguel Auza'),
('COA', 'Saltillo'),
('CHH', 'Guazapares'),
('CHP', 'Chicomuselo'),
('DUR', 'San Pedro del Gallo'),
('GRO', 'Florencio Villarreal'),
('GUA', 'San Felipe'),
('HID', 'Ixmiquilpan'),
('JAL', 'Chapala'),
('MEX', 'Chiconcuac'),
('MIC', 'Ecuandureo'),
('MOR', 'Yecapixtla'),
('NLE', 'Iturbide'),
('OAX', 'El Espinal'),
('PUE', 'Coatepec'),
('SLP', 'San Nicolás Tolentino'),
('SON', 'Hermosillo'),
('TAM', 'Padilla'),
('TLA', 'Terrenate'),
('VER', 'Camerino Z. Mendoza'),
('YUC', 'Dzitás'),
('ZAC', 'Momax'),
('COA', 'San Buenaventura'),
('CHH', 'Guerrero'),
('CHP', 'Chilón'),
('DUR', 'Santa Clara'),
('GRO', 'General Canuto A. Neri'),
('GUA', 'San Francisco del Rincón'),
('HID', 'Jacala de Ledezma'),
('JAL', 'Chimaltitán'),
('MEX', 'Chimalhuacán'),
('MIC', 'Epitacio Huerta'),
('MOR', 'Zacatepec'),
('NLE', 'Juárez'),
('OAX', 'Tamazulápam del Espíritu Santo'),
('PUE', 'Coatzingo'),
('SLP', 'Santa Catarina'),
('SON', 'Huachinera'),
('TAM', 'Palmillas'),
('TLA', 'Tetla de la Solidaridad'),
('VER', 'Carrillo Puerto'),
('YUC', 'Dzoncauich'),
('ZAC', 'Monte Escobedo'),
('COA', 'San Juan de Sabinas'),
('CHH', 'Hidalgo del Parral'),
('CHP', 'Escuintla'),
('DUR', 'Santiago Papasquiaro'),
('GRO', 'General Heliodoro Castillo'),
('GUA', 'San José Iturbide'),
('HID', 'Jaltocán'),
('JAL', 'Chiquilistlán'),
('MEX', 'Donato Guerra'),
('MIC', 'Erongarícuaro'),
('MOR', 'Zacualpan'),
('NLE', 'Lampazos de Naranjo'),
('OAX', 'Fresnillo de Trujano'),
('PUE', 'Cohetzala'),
('SLP', 'Santa María del Río'),
('SON', 'Huásabas'),
('TAM', 'Reynosa'),
('TLA', 'Tetlatlahuca'),
('VER', 'Catemaco'),
('YUC', 'Espita'),
('ZAC', 'Morelos'),
('COA', 'San Pedro'),
('CHH', 'Huejotitán'),
('CHP', 'Francisco León'),
('DUR', 'Súchil'),
('GRO', 'Huamuxtitlán'),
('GUA', 'San Luis de la Paz'),
('HID', 'Juárez Hidalgo'),
('JAL', 'Degollado'),
('MEX', 'Ecatepec de Morelos'),
('MIC', 'Gabriel Zamora'),
('MOR', 'Temoac'),
('NLE', 'Linares'),
('OAX', 'Guadalupe Etla'),
('PUE', 'Cohuecan'),
('SLP', 'Santo Domingo'),
('SON', 'Huatabampo'),
('TAM', 'Río Bravo'),
('TLA', 'Tlaxcala'),
('VER', 'Cazones de Herrera'),
('YUC', 'Halachó'),
('ZAC', 'Moyahua de Estrada'),
('COA', 'Sierra Mojada'),
('CHH', 'Ignacio Zaragoza'),
('CHP', 'Frontera Comalapa'),
('DUR', 'Tamazula'),
('GRO', 'Huitzuco de los Figueroa'),
('GUA', 'Santa Catarina'),
('HID', 'Lolotla'),
('JAL', 'Ejutla'),
('MEX', 'Ecatzingo'),
('MIC', 'Hidalgo'),
('NLE', 'Marín'),
('OAX', 'Guadalupe de Ramírez'),
('PUE', 'Coronango'),
('SLP', 'San Vicente Tancuayalab'),
('SON', 'Huépac'),
('TAM', 'San Carlos'),
('TLA', 'Tlaxco'),
('VER', 'Cerro Azul'),
('YUC', 'Hocabá'),
('ZAC', 'Nochistlán de Mejía'),
('COA', 'Torreón'),
('CHH', 'Janos'),
('CHP', 'Frontera Hidalgo'),
('DUR', 'Tepehuanes'),
('GRO', 'Iguala de la Independencia'),
('GUA', 'Santa Cruz de Juventino Rosas'),
('HID', 'Metepec'),
('JAL', 'Encarnación de Díaz'),
('MEX', 'Huehuetoca'),
('MIC', 'La Huacana'),
('NLE', 'Melchor Ocampo'),
('OAX', 'Guelatao de Juárez'),
('PUE', 'Coxcatlán'),
('SLP', 'Soledad de Graciano Sánchez'),
('SON', 'Imuris'),
('TAM', 'San Fernando'),
('TLA', 'Tocatlán'),
('VER', 'Citlaltépetl'),
('YUC', 'Hoctún'),
('ZAC', 'Noria de Ángeles'),
('COA', 'Viesca'),
('CHH', 'Jiménez'),
('CHP', 'La Grandeza'),
('DUR', 'Tlahualilo'),
('GRO', 'Igualapa'),
('GUA', 'Santiago Maravatío'),
('HID', 'San Agustín Metzquititlán'),
('JAL', 'Etzatlán'),
('MEX', 'Hueypoxtla'),
('MIC', 'Huandacareo'),
('NLE', 'Mier y Noriega'),
('OAX', 'Guevea de Humboldt'),
('PUE', 'Coyomeapan'),
('SLP', 'Tamasopo'),
('SON', 'Magdalena'),
('TAM', 'San Nicolás'),
('TLA', 'Totolac'),
('VER', 'Coacoatzintla'),
('YUC', 'Homún'),
('ZAC', 'Ojocaliente'),
('COA', 'Villa Unión'),
('CHH', 'Juárez'),
('CHP', 'Huehuetán'),
('DUR', 'Topia'),
('GRO', 'Ixcateopan de Cuauhtémoc'),
('GUA', 'Silao de la Victoria'),
('HID', 'Metztitlán'),
('JAL', 'El Grullo'),
('MEX', 'Huixquilucan'),
('MIC', 'Huaniqueo'),
('NLE', 'Mina'),
('OAX', 'Mesones Hidalgo'),
('PUE', 'Coyotepec'),
('SLP', 'Tamazunchale'),
('SON', 'Mazatán'),
('TAM', 'Soto la Marina'),
('TLA', 'Ziltlaltépec de Trinidad Sánchez Santos'),
('VER', 'Coahuitlán'),
('YUC', 'Huhí'),
('ZAC', 'Pánuco'),
('COA', 'Zaragoza'),
('CHH', 'Julimes'),
('CHP', 'Huixtán'),
('DUR', 'Vicente Guerrero'),
('GRO', 'Zihuatanejo de Azueta'),
('GUA', 'Tarandacuao'),
('HID', 'Mineral del Chico'),
('JAL', 'Guachinango'),
('MEX', 'Isidro Fabela'),
('MIC', 'Huetamo'),
('NLE', 'Montemorelos'),
('OAX', 'Villa Hidalgo'),
('PUE', 'Cuapiaxtla de Madero'),
('SLP', 'Tampacán'),
('SON', 'Moctezuma'),
('TAM', 'Tampico'),
('TLA', 'Tzompantepec'),
('VER', 'Coatepec'),
('YUC', 'Hunucmá'),
('ZAC', 'Pinos'),
('CHH', 'López'),
('CHP', 'Huitiupán'),
('DUR', 'Nuevo Ideal'),
('GRO', 'Juan R. Escudero'),
('GUA', 'Tarimoro'),
('HID', 'Mineral del Monte'),
('JAL', 'Guadalajara'),
('MEX', 'Ixtapaluca'),
('MIC', 'Huiramba'),
('NLE', 'Monterrey'),
('OAX', 'Heroica Ciudad de Huajuapan de León'),
('PUE', 'Cuautempan'),
('SLP', 'Tampamolón Corona'),
('SON', 'Naco'),
('TAM', 'Tula'),
('TLA', 'Xaloztoc'),
('VER', 'Coatzacoalcos'),
('YUC', 'Ixil'),
('ZAC', 'Río Grande'),
('CHH', 'Madera'),
('CHP', 'Huixtla'),
('GRO', 'Leonardo Bravo'),
('GUA', 'Tierra Blanca'),
('HID', 'La Misión'),
('JAL', 'Hostotipaquillo'),
('MEX', 'Ixtapan de la Sal'),
('MIC', 'Indaparapeo'),
('NLE', 'Parás'),
('OAX', 'Huautepec'),
('PUE', 'Cuautinchán'),
('SLP', 'Tamuín'),
('SON', 'Nácori Chico'),
('TAM', 'Valle Hermoso'),
('TLA', 'Xaltocan'),
('VER', 'Coatzintla'),
('YUC', 'Izamal'),
('ZAC', 'Sain Alto'),
('CHH', 'Maguarichi'),
('CHP', 'La Independencia'),
('GRO', 'Malinaltepec'),
('GUA', 'Uriangato'),
('HID', 'Mixquiahuala de Juárez'),
('JAL', 'Huejúcar'),
('MEX', 'Ixtapan del Oro'),
('MIC', 'Irimbo'),
('NLE', 'Pesquería'),
('OAX', 'Huautla de Jiménez'),
('PUE', 'Cuautlancingo'),
('SLP', 'Tanlajás'),
('SON', 'Nacozari de García'),
('TAM', 'Victoria'),
('TLA', 'Papalotla de Xicohténcatl'),
('VER', 'Coetzala'),
('YUC', 'Kanasín'),
('ZAC', 'El Salvador'),
('CHH', 'Manuel Benavides'),
('CHP', 'Ixhuatán'),
('GRO', 'Mártir de Cuilapan'),
('GUA', 'Valle de Santiago'),
('HID', 'Molango de Escamilla'),
('JAL', 'Huejuquilla el Alto'),
('MEX', 'Ixtlahuaca'),
('MIC', 'Ixtlán'),
('NLE', 'Los Ramones'),
('OAX', 'Ixtlán de Juárez'),
('PUE', 'Cuayuca de Andrade'),
('SLP', 'Tanquián de Escobedo'),
('SON', 'Navojoa'),
('TAM', 'Villagrán'),
('TLA', 'Xicohtzinco'),
('VER', 'Colipa'),
('YUC', 'Kantunil'),
('ZAC', 'Sombrerete'),
('CHH', 'Matachí'),
('CHP', 'Ixtacomitán'),
('GRO', 'Metlatónoc'),
('GUA', 'Victoria'),
('HID', 'Nicolás Flores'),
('JAL', 'La Huerta'),
('MEX', 'Xalatlaco'),
('MIC', 'Jacona'),
('NLE', 'Rayones'),
('OAX', 'Heroica Ciudad de Juchitán de Zaragoza'),
('PUE', 'Cuetzalan del Progreso'),
('SLP', 'Tierra Nueva'),
('SON', 'Nogales'),
('TAM', 'Xicoténcatl'),
('TLA', 'Yauhquemehcan'),
('VER', 'Comapa'),
('YUC', 'Kaua'),
('ZAC', 'Susticacán'),
('CHH', 'Matamoros'),
('CHP', 'Ixtapa'),
('GRO', 'Mochitlán'),
('GUA', 'Villagrán'),
('HID', 'Nopala de Villagrán'),
('JAL', 'Ixtlahuacán de los Membrillos'),
('MEX', 'Jaltenco'),
('MIC', 'Jiménez'),
('NLE', 'Sabinas Hidalgo'),
('OAX', 'Loma Bonita'),
('PUE', 'Cuyoaco'),
('SLP', 'Vanegas'),
('SON', 'Onavas'),
('TLA', 'Zacatelco'),
('VER', 'Córdoba'),
('YUC', 'Kinchil'),
('ZAC', 'Tabasco'),
('CHH', 'Meoqui'),
('CHP', 'Ixtapangajoya'),
('GRO', 'Olinalá'),
('GUA', 'Xichú'),
('HID', 'Omitlán de Juárez'),
('JAL', 'Ixtlahuacán del Río'),
('MEX', 'Jilotepec'),
('MIC', 'Jiquilpan'),
('NLE', 'Salinas Victoria'),
('OAX', 'Magdalena Apasco'),
('PUE', 'Chalchicomula de Sesma'),
('SLP', 'Venado'),
('SON', 'Opodepe'),
('TLA', 'Benito Juárez'),
('VER', 'Cosamaloapan de Carpio'),
('YUC', 'Kopomá'),
('ZAC', 'Tepechitlán'),
('CHH', 'Morelos'),
('CHP', 'Jiquipilas'),
('GRO', 'Ometepec'),
('GUA', 'Yuriria'),
('HID', 'San Felipe Orizatlán'),
('JAL', 'Jalostotitlán'),
('MEX', 'Jilotzingo'),
('MIC', 'Juárez'),
('NLE', 'San Nicolás de los Garza'),
('OAX', 'Magdalena Jaltepec'),
('PUE', 'Chapulco'),
('SLP', 'Villa de Arriaga'),
('SON', 'Oquitoa'),
('TLA', 'Emiliano Zapata'),
('VER', 'Cosautlán de Carvajal'),
('YUC', 'Mama'),
('ZAC', 'Tepetongo'),
('CHH', 'Moris'),
('CHP', 'Jitotol'),
('GRO', 'Pedro Ascencio Alquisiras'),
('HID', 'Pacula'),
('JAL', 'Jamay'),
('MEX', 'Jiquipilco'),
('MIC', 'Jungapeo'),
('NLE', 'Hidalgo'),
('OAX', 'Santa Magdalena Jicotlán'),
('PUE', 'Chiautla'),
('SLP', 'Villa de Guadalupe'),
('SON', 'Pitiquito'),
('TLA', 'Lázaro Cárdenas'),
('VER', 'Coscomatepec'),
('YUC', 'Maní'),
('ZAC', 'Teúl de González Ortega'),
('CHH', 'Namiquipa'),
('CHP', 'Juárez'),
('GRO', 'Petatlán'),
('HID', 'Pachuca de Soto'),
('JAL', 'Jesús María'),
('MEX', 'Jocotitlán'),
('MIC', 'Lagunillas'),
('NLE', 'Santa Catarina'),
('OAX', 'Magdalena Mixtepec'),
('PUE', 'Chiautzingo'),
('SLP', 'Villa de la Paz'),
('SON', 'Puerto Peñasco'),
('TLA', 'La Magdalena Tlaltelulco'),
('VER', 'Cosoleacaque'),
('YUC', 'Maxcanú'),
('ZAC', 'Tlaltenango de Sánchez Román'),
('CHH', 'Nonoava'),
('CHP', 'Larráinzar'),
('GRO', 'Pilcaya'),
('HID', 'Pisaflores'),
('JAL', 'Jilotlán de los Dolores'),
('MEX', 'Joquicingo'),
('MIC', 'Madero'),
('NLE', 'Santiago'),
('OAX', 'Magdalena Ocotlán'),
('PUE', 'Chiconcuautla'),
('SLP', 'Villa de Ramos'),
('SON', 'Quiriego'),
('TLA', 'San Damián Texóloc'),
('VER', 'Cotaxtla'),
('YUC', 'Mayapán'),
('ZAC', 'Valparaíso'),
('CHH', 'Nuevo Casas Grandes'),
('CHP', 'La Libertad'),
('GRO', 'Pungarabato'),
('HID', 'Progreso de Obregón'),
('JAL', 'Jocotepec'),
('MEX', 'Juchitepec'),
('MIC', 'Maravatío'),
('NLE', 'Vallecillo'),
('OAX', 'Magdalena Peñasco'),
('PUE', 'Chichiquila'),
('SLP', 'Villa de Reyes'),
('SON', 'Rayón'),
('TLA', 'San Francisco Tetlanohcan'),
('VER', 'Coxquihui'),
('YUC', 'Mérida'),
('ZAC', 'Vetagrande'),
('CHH', 'Ocampo'),
('CHP', 'Mapastepec'),
('GRO', 'Quechultenango'),
('HID', 'Mineral de la Reforma'),
('JAL', 'Juanacatlán'),
('MEX', 'Lerma'),
('MIC', 'Marcos Castellanos'),
('NLE', 'Villaldama'),
('OAX', 'Magdalena Teitipac'),
('PUE', 'Chietla'),
('SLP', 'Villa Hidalgo'),
('SON', 'Rosario'),
('TLA', 'San Jerónimo Zacualpan'),
('VER', 'Coyutla'),
('YUC', 'Mocochá'),
('ZAC', 'Villa de Cos'),
('CHH', 'Ojinaga'),
('CHP', 'Las Margaritas'),
('GRO', 'San Luis Acatlán'),
('HID', 'San Agustín Tlaxiaca'),
('JAL', 'Juchitlán'),
('MEX', 'Malinalco'),
('MIC', 'Lázaro Cárdenas'),
('OAX', 'Magdalena Tequisistlán'),
('PUE', 'Chigmecatitlán'),
('SLP', 'Villa Juárez'),
('SON', 'Sahuaripa'),
('TLA', 'San José Teacalco'),
('VER', 'Cuichapa'),
('YUC', 'Motul'),
('ZAC', 'Villa García'),
('CHH', 'Praxedis G. Guerrero'),
('CHP', 'Mazapa de Madero'),
('GRO', 'San Marcos'),
('HID', 'San Bartolo Tutotepec'),
('JAL', 'Lagos de Moreno'),
('MEX', 'Melchor Ocampo'),
('MIC', 'Morelia'),
('OAX', 'Magdalena Tlacotepec'),
('PUE', 'Chignahuapan'),
('SLP', 'Axtla de Terrazas'),
('SON', 'San Felipe de Jesús'),
('TLA', 'San Juan Huactzinco'),
('VER', 'Cuitláhuac'),
('YUC', 'Muna'),
('ZAC', 'Villa González Ortega'),
('CHH', 'Riva Palacio'),
('CHP', 'Mazatán'),
('GRO', 'San Miguel Totolapan'),
('HID', 'San Salvador'),
('JAL', 'El Limón'),
('MEX', 'Metepec'),
('MIC', 'Morelos'),
('OAX', 'Magdalena Zahuatlán'),
('PUE', 'Chignautla'),
('SLP', 'Xilitla'),
('SON', 'San Javier'),
('TLA', 'San Lorenzo Axocomanitla'),
('VER', 'Chacaltianguis'),
('YUC', 'Muxupip'),
('ZAC', 'Villa Hidalgo'),
('CHH', 'Rosales'),
('CHP', 'Metapa'),
('GRO', 'Taxco de Alarcón'),
('HID', 'Santiago de Anaya'),
('JAL', 'Magdalena'),
('MEX', 'Mexicaltzingo'),
('MIC', 'Múgica'),
('OAX', 'Mariscala de Juárez'),
('PUE', 'Chila'),
('SLP', 'Zaragoza'),
('SON', 'San Luis Río Colorado'),
('TLA', 'San Lucas Tecopilco'),
('VER', 'Chalma'),
('YUC', 'Opichén'),
('ZAC', 'Villanueva'),
('CHH', 'Rosario'),
('CHP', 'Mitontic'),
('GRO', 'Tecoanapa'),
('HID', 'Santiago Tulantepec de Lugo Guerrero'),
('JAL', 'Santa María del Oro'),
('MEX', 'Morelos'),
('MIC', 'Nahuatzen'),
('OAX', 'Mártires de Tacubaya'),
('PUE', 'Chila de la Sal'),
('SLP', 'Villa de Arista'),
('SON', 'San Miguel de Horcasitas'),
('TLA', 'Santa Ana Nopalucan'),
('VER', 'Chiconamel'),
('YUC', 'Oxkutzcab'),
('ZAC', 'Zacatecas'),
('CHH', 'San Francisco de Borja'),
('CHP', 'Motozintla'),
('GRO', 'Técpan de Galeana'),
('HID', 'Singuilucan'),
('JAL', 'La Manzanilla de la Paz'),
('MEX', 'Naucalpan de Juárez'),
('MIC', 'Nocupétaro'),
('OAX', 'Matías Romero Avendaño'),
('PUE', 'Honey'),
('SLP', 'Matlapa'),
('SON', 'San Pedro de la Cueva'),
('TLA', 'Santa Apolonia Teacalco'),
('VER', 'Chiconquiaco'),
('YUC', 'Panabá'),
('ZAC', 'Trancoso'),
('CHH', 'San Francisco de Conchos'),
('CHP', 'Nicolás Ruíz'),
('GRO', 'Teloloapan'),
('HID', 'Tasquillo'),
('JAL', 'Mascota'),
('MEX', 'Nezahualcóyotl'),
('MIC', 'Nuevo Parangaricutiro'),
('OAX', 'Mazatlán Villa de Flores'),
('PUE', 'Chilchotla'),
('SLP', 'El Naranjo'),
('SON', 'Santa Ana'),
('TLA', 'Santa Catarina Ayometla'),
('VER', 'Chicontepec'),
('YUC', 'Peto'),
('ZAC', 'Santa María de la Paz'),
('CHH', 'San Francisco del Oro'),
('CHP', 'Ocosingo'),
('GRO', 'Tepecoacuilco de Trujano'),
('HID', 'Tecozautla'),
('JAL', 'Mazamitla'),
('MEX', 'Nextlalpan'),
('MIC', 'Nuevo Urecho'),
('OAX', 'Miahuatlán de Porfirio Díaz'),
('PUE', 'Chinantla'),
('SON', 'Santa Cruz'),
('TLA', 'Santa Cruz Quilehtla'),
('VER', 'Chinameca'),
('YUC', 'Progreso'),
('CHH', 'Santa Bárbara'),
('CHP', 'Ocotepec'),
('GRO', 'Tetipac'),
('HID', 'Tenango de Doria'),
('JAL', 'Mexticacán'),
('MEX', 'Nicolás Romero'),
('MIC', 'Numarán'),
('OAX', 'Mixistlán de la Reforma'),
('PUE', 'Domingo Arenas'),
('SON', 'Sáric'),
('TLA', 'Santa Isabel Xiloxoxtla'),
('VER', 'Chinampa de Gorostiza'),
('YUC', 'Quintana Roo'),
('CHH', 'Satevó'),
('CHP', 'Ocozocoautla de Espinosa'),
('GRO', 'Tixtla de Guerrero'),
('HID', 'Tepeapulco'),
('JAL', 'Mezquitic'),
('MEX', 'Nopaltepec'),
('MIC', 'Ocampo'),
('OAX', 'Monjas'),
('PUE', 'Eloxochitlán'),
('SON', 'Soyopa'),
('VER', 'Las Choapas'),
('YUC', 'Río Lagartos'),
('CHH', 'Saucillo'),
('CHP', 'Ostuacán'),
('GRO', 'Tlacoachistlahuaca'),
('HID', 'Tepehuacán de Guerrero'),
('JAL', 'Mixtlán'),
('MEX', 'Ocoyoacac'),
('MIC', 'Pajacuarán'),
('OAX', 'Natividad'),
('PUE', 'Epatlán'),
('SON', 'Suaqui Grande'),
('VER', 'Chocamán'),
('YUC', 'Sacalum'),
('CHH', 'Temósachic'),
('CHP', 'Osumacinta'),
('GRO', 'Tlacoapa'),
('HID', 'Tepeji del Río de Ocampo'),
('JAL', 'Ocotlán'),
('MEX', 'Ocuilan'),
('MIC', 'Panindícuaro'),
('OAX', 'Nazareno Etla'),
('PUE', 'Esperanza'),
('SON', 'Tepache'),
('VER', 'Chontla'),
('YUC', 'Samahil'),
('CHH', 'El Tule'),
('CHP', 'Oxchuc'),
('GRO', 'Tlalchapa'),
('HID', 'Tepetitlán'),
('JAL', 'Ojuelos de Jalisco'),
('MEX', 'El Oro'),
('MIC', 'Parácuaro'),
('OAX', 'Nejapa de Madero'),
('PUE', 'Francisco Z. Mena'),
('SON', 'Trincheras'),
('VER', 'Chumatlán'),
('YUC', 'Sanahcat'),
('CHH', 'Urique'),
('CHP', 'Palenque'),
('GRO', 'Tlalixtaquilla de Maldonado'),
('HID', 'Tetepango'),
('JAL', 'Pihuamo'),
('MEX', 'Otumba'),
('MIC', 'Paracho'),
('OAX', 'Ixpantepec Nieves'),
('PUE', 'General Felipe Ángeles'),
('SON', 'Tubutama'),
('VER', 'Emiliano Zapata'),
('YUC', 'San Felipe'),
('CHH', 'Uruachi'),
('CHP', 'Pantelhó'),
('GRO', 'Tlapa de Comonfort'),
('HID', 'Villa de Tezontepec'),
('JAL', 'Poncitlán'),
('MEX', 'Otzoloapan'),
('MIC', 'Pátzcuaro'),
('OAX', 'Santiago Niltepec'),
('PUE', 'Guadalupe'),
('SON', 'Ures'),
('VER', 'Espinal'),
('YUC', 'Santa Elena'),
('CHH', 'Valle de Zaragoza'),
('CHP', 'Pantepec'),
('GRO', 'Tlapehuala'),
('HID', 'Tezontepec de Aldama'),
('JAL', 'Puerto Vallarta'),
('MEX', 'Otzolotepec'),
('MIC', 'Penjamillo'),
('OAX', 'Oaxaca de Juárez'),
('PUE', 'Guadalupe Victoria'),
('SON', 'Villa Hidalgo'),
('VER', 'Filomeno Mata'),
('YUC', 'Seyé'),
('CHP', 'Pichucalco'),
('GRO', 'La Unión de Isidoro Montes de Oca'),
('HID', 'Tianguistengo'),
('JAL', 'Villa Purificación'),
('MEX', 'Ozumba'),
('MIC', 'Peribán'),
('OAX', 'Ocotlán de Morelos'),
('PUE', 'Hermenegildo Galeana'),
('SON', 'Villa Pesqueira'),
('VER', 'Fortín'),
('YUC', 'Sinanché'),
('CHP', 'Pijijiapan'),
('GRO', 'Xalpatláhuac'),
('HID', 'Tizayuca'),
('JAL', 'Quitupan'),
('MEX', 'Papalotla'),
('MIC', 'La Piedad'),
('OAX', 'La Pe'),
('PUE', 'Huaquechula'),
('SON', 'Yécora'),
('VER', 'Gutiérrez Zamora'),
('YUC', 'Sotuta'),
('CHP', 'El Porvenir'),
('GRO', 'Xochihuehuetlán'),
('HID', 'Tlahuelilpan'),
('JAL', 'El Salto'),
('MEX', 'La Paz'),
('MIC', 'Purépero'),
('OAX', 'Pinotepa de Don Luis'),
('PUE', 'Huatlatlauca'),
('SON', 'General Plutarco Elías Calles'),
('VER', 'Hidalgotitlán'),
('YUC', 'Sucilá'),
('CHP', 'Villa Comaltitlán'),
('GRO', 'Xochistlahuaca'),
('HID', 'Tlahuiltepa'),
('JAL', 'San Cristóbal de la Barranca'),
('MEX', 'Polotitlán'),
('MIC', 'Puruándiro'),
('OAX', 'Pluma Hidalgo'),
('PUE', 'Huauchinango'),
('SON', 'Benito Juárez'),
('VER', 'Huatusco'),
('YUC', 'Sudzal'),
('CHP', 'Pueblo Nuevo Solistahuacán'),
('GRO', 'Zapotitlán Tablas'),
('HID', 'Tlanalapa'),
('JAL', 'San Diego de Alejandría'),
('MEX', 'Rayón'),
('MIC', 'Queréndaro'),
('OAX', 'San José del Progreso'),
('PUE', 'Huehuetla'),
('SON', 'San Ignacio Río Muerto'),
('VER', 'Huayacocotla'),
('YUC', 'Suma'),
('CHP', 'Rayón'),
('GRO', 'Zirándaro'),
('HID', 'Tlanchinol'),
('JAL', 'San Juan de los Lagos'),
('MEX', 'San Antonio la Isla'),
('MIC', 'Quiroga'),
('OAX', 'Putla Villa de Guerrero'),
('PUE', 'Huehuetlán el Chico'),
('VER', 'Hueyapan de Ocampo'),
('YUC', 'Tahdziú'),
('CHP', 'Reforma'),
('GRO', 'Zitlala'),
('HID', 'Tlaxcoapan'),
('JAL', 'San Julián'),
('MEX', 'San Felipe del Progreso'),
('MIC', 'Cojumatlán de Régules'),
('OAX', 'Santa Catarina Quioquitani'),
('PUE', 'Huejotzingo'),
('VER', 'Huiloapan de Cuauhtémoc'),
('YUC', 'Tahmek'),
('CHP', 'Las Rosas'),
('GRO', 'Eduardo Neri'),
('HID', 'Tolcayuca'),
('JAL', 'San Marcos'),
('MEX', 'San Martín de las Pirámides'),
('MIC', 'Los Reyes'),
('OAX', 'Reforma de Pineda'),
('PUE', 'Hueyapan'),
('VER', 'Ignacio de la Llave'),
('YUC', 'Teabo'),
('CHP', 'Sabanilla'),
('GRO', 'Acatepec'),
('HID', 'Tula de Allende'),
('JAL', 'San Martín de Bolaños'),
('MEX', 'San Mateo Atenco'),
('MIC', 'Sahuayo'),
('OAX', 'La Reforma'),
('PUE', 'Hueytamalco'),
('VER', 'Ilamatlán'),
('YUC', 'Tecoh'),
('CHP', 'Salto de Agua'),
('GRO', 'Marquelia'),
('HID', 'Tulancingo de Bravo'),
('JAL', 'San Martín Hidalgo'),
('MEX', 'San Simón de Guerrero'),
('MIC', 'San Lucas'),
('OAX', 'Reyes Etla'),
('PUE', 'Hueytlalpan'),
('VER', 'Isla'),
('YUC', 'Tekal de Venegas'),
('CHP', 'San Cristóbal de las Casas'),
('GRO', 'Cochoapa el Grande'),
('HID', 'Xochiatipan'),
('JAL', 'San Miguel el Alto'),
('MEX', 'Santo Tomás'),
('MIC', 'Santa Ana Maya'),
('OAX', 'Rojas de Cuauhtémoc'),
('PUE', 'Huitzilan de Serdán'),
('VER', 'Ixcatepec'),
('YUC', 'Tekantó'),
('CHP', 'San Fernando'),
('GRO', 'José Joaquín de Herrera'),
('HID', 'Xochicoatlán'),
('JAL', 'Gómez Farías'),
('MEX', 'Soyaniquilpan de Juárez'),
('MIC', 'Salvador Escalante'),
('OAX', 'Salina Cruz'),
('PUE', 'Huitziltepec'),
('VER', 'Ixhuacán de los Reyes'),
('YUC', 'Tekax'),
('CHP', 'Siltepec'),
('GRO', 'Juchitán'),
('HID', 'Yahualica'),
('JAL', 'San Sebastián del Oeste'),
('MEX', 'Sultepec'),
('MIC', 'Senguio'),
('OAX', 'San Agustín Amatengo'),
('PUE', 'Atlequizayan'),
('VER', 'Ixhuatlán del Café'),
('YUC', 'Tekit'),
('CHP', 'Simojovel'),
('GRO', 'Iliatenco'),
('HID', 'Zacualtipán de Ángeles'),
('JAL', 'Santa María de los Ángeles'),
('MEX', 'Tecámac'),
('MIC', 'Susupuato'),
('OAX', 'San Agustín Atenango'),
('PUE', 'Ixcamilpa de Guerrero'),
('VER', 'Ixhuatlancillo'),
('YUC', 'Tekom'),
('CHP', 'Sitalá'),
('HID', 'Zapotlán de Juárez'),
('JAL', 'Sayula'),
('MEX', 'Tejupilco'),
('MIC', 'Tacámbaro'),
('OAX', 'San Agustín Chayuco'),
('PUE', 'Ixcaquixtla'),
('VER', 'Ixhuatlán del Sureste'),
('YUC', 'Telchac Pueblo'),
('CHP', 'Socoltenango'),
('HID', 'Zempoala'),
('JAL', 'Tala'),
('MEX', 'Temamatla'),
('MIC', 'Tancítaro'),
('OAX', 'San Agustín de las Juntas'),
('PUE', 'Ixtacamaxtitlán'),
('VER', 'Ixhuatlán de Madero'),
('YUC', 'Telchac Puerto'),
('CHP', 'Solosuchiapa'),
('HID', 'Zimapán'),
('JAL', 'Talpa de Allende'),
('MEX', 'Temascalapa'),
('MIC', 'Tangamandapio'),
('OAX', 'San Agustín Etla'),
('PUE', 'Ixtepec'),
('VER', 'Ixmatlahuacan'),
('YUC', 'Temax'),
('CHP', 'Soyaló'),
('JAL', 'Tamazula de Gordiano'),
('MEX', 'Temascalcingo'),
('MIC', 'Tangancícuaro'),
('OAX', 'San Agustín Loxicha'),
('PUE', 'Izúcar de Matamoros'),
('VER', 'Ixtaczoquitlán'),
('YUC', 'Temozón'),
('CHP', 'Suchiapa'),
('JAL', 'Tapalpa'),
('MEX', 'Temascaltepec'),
('MIC', 'Tanhuato'),
('OAX', 'San Agustín Tlacotepec'),
('PUE', 'Jalpan'),
('VER', 'Jalacingo'),
('YUC', 'Tepakán'),
('CHP', 'Suchiate'),
('JAL', 'Tecalitlán'),
('MEX', 'Temoaya'),
('MIC', 'Taretan'),
('OAX', 'San Agustín Yatareni'),
('PUE', 'Jolalpan'),
('VER', 'Xalapa'),
('YUC', 'Tetiz'),
('CHP', 'Sunuapa'),
('JAL', 'Tecolotlán'),
('MEX', 'Tenancingo'),
('MIC', 'Tarímbaro'),
('OAX', 'San Andrés Cabecera Nueva'),
('PUE', 'Jonotla'),
('VER', 'Jalcomulco'),
('YUC', 'Teya'),
('CHP', 'Tapachula'),
('JAL', 'Techaluta de Montenegro'),
('MEX', 'Tenango del Aire'),
('MIC', 'Tepalcatepec'),
('OAX', 'San Andrés Dinicuiti'),
('PUE', 'Jopala'),
('VER', 'Jáltipan'),
('YUC', 'Ticul'),
('CHP', 'Tapalapa'),
('JAL', 'Tenamaxtlán'),
('MEX', 'Tenango del Valle'),
('MIC', 'Tingambato'),
('OAX', 'San Andrés Huaxpaltepec'),
('PUE', 'Juan C. Bonilla'),
('VER', 'Jamapa'),
('YUC', 'Timucuy'),
('CHP', 'Tapilula'),
('JAL', 'Teocaltiche'),
('MEX', 'Teoloyucan'),
('MIC', 'Tingüindín'),
('OAX', 'San Andrés Huayápam'),
('PUE', 'Juan Galindo'),
('VER', 'Jesús Carranza'),
('YUC', 'Tinum'),
('CHP', 'Tecpatán'),
('JAL', 'Teocuitatlán de Corona'),
('MEX', 'Teotihuacán'),
('MIC', 'Tiquicheo de Nicolás Romero'),
('OAX', 'San Andrés Ixtlahuaca'),
('PUE', 'Juan N. Méndez'),
('VER', 'Xico'),
('YUC', 'Tixcacalcupul'),
('CHP', 'Tenejapa'),
('JAL', 'Tepatitlán de Morelos'),
('MEX', 'Tepetlaoxtoc'),
('MIC', 'Tlalpujahua'),
('OAX', 'San Andrés Lagunas'),
('PUE', 'Lafragua'),
('VER', 'Jilotepec'),
('YUC', 'Tixkokob'),
('CHP', 'Teopisca'),
('JAL', 'Tequila'),
('MEX', 'Tepetlixpa'),
('MIC', 'Tlazazalca'),
('OAX', 'San Andrés Nuxiño'),
('PUE', 'Libres'),
('VER', 'Juan Rodríguez Clara'),
('YUC', 'Tixmehuac'),
('JAL', 'Teuchitlán'),
('MEX', 'Tepotzotlán'),
('MIC', 'Tocumbo'),
('OAX', 'San Andrés Paxtlán'),
('PUE', 'La Magdalena Tlatlauquitepec'),
('VER', 'Juchique de Ferrer'),
('YUC', 'Tixpéhual'),
('CHP', 'Tila'),
('JAL', 'Tizapán el Alto'),
('MEX', 'Tequixquiac'),
('MIC', 'Tumbiscatío'),
('OAX', 'San Andrés Sinaxtla'),
('PUE', 'Mazapiltepec de Juárez'),
('VER', 'Landero y Coss'),
('YUC', 'Tizimín'),
('CHP', 'Tonalá'),
('JAL', 'Tlajomulco de Zúñiga'),
('MEX', 'Texcaltitlán'),
('MIC', 'Turicato'),
('OAX', 'San Andrés Solaga'),
('PUE', 'Mixtla'),
('VER', 'Lerdo de Tejada'),
('YUC', 'Tunkás'),
('CHP', 'Totolapa'),
('JAL', 'San Pedro Tlaquepaque'),
('MEX', 'Texcalyacac'),
('MIC', 'Tuxpan'),
('OAX', 'San Andrés Teotilálpam'),
('PUE', 'Molcaxac'),
('VER', 'Magdalena'),
('YUC', 'Tzucacab'),
('CHP', 'La Trinitaria'),
('JAL', 'Tolimán'),
('MEX', 'Texcoco'),
('MIC', 'Tuzantla'),
('OAX', 'San Andrés Tepetlapa'),
('PUE', 'Cañada Morelos'),
('VER', 'Maltrata'),
('YUC', 'Uayma'),
('CHP', 'Tumbalá'),
('JAL', 'Tomatlán'),
('MEX', 'Tezoyuca'),
('MIC', 'Tzintzuntzan'),
('OAX', 'San Andrés Yaá'),
('PUE', 'Naupan'),
('VER', 'Manlio Fabio Altamirano'),
('YUC', 'Ucú'),
('CHP', 'Tuxtla Gutiérrez'),
('JAL', 'Tonalá'),
('MEX', 'Tianguistenco'),
('MIC', 'Tzitzio'),
('OAX', 'San Andrés Zabache'),
('PUE', 'Nauzontla'),
('VER', 'Mariano Escobedo'),
('YUC', 'Umán'),
('CHP', 'Tuxtla Chico'),
('JAL', 'Tonaya'),
('MEX', 'Timilpan'),
('MIC', 'Uruapan'),
('OAX', 'San Andrés Zautla'),
('PUE', 'Nealtican'),
('VER', 'Martínez de la Torre'),
('YUC', 'Valladolid'),
('CHP', 'Tuzantán'),
('JAL', 'Tonila'),
('MEX', 'Tlalmanalco'),
('MIC', 'Venustiano Carranza'),
('OAX', 'San Antonino Castillo Velasco'),
('PUE', 'Nicolás Bravo'),
('VER', 'Mecatlán'),
('YUC', 'Xocchel'),
('CHP', 'Tzimol'),
('JAL', 'Totatiche'),
('MEX', 'Tlalnepantla de Baz'),
('MIC', 'Villamar'),
('OAX', 'San Antonino el Alto'),
('PUE', 'Nopalucan'),
('VER', 'Mecayapan'),
('YUC', 'Yaxcabá'),
('CHP', 'Unión Juárez'),
('JAL', 'Tototlán'),
('MEX', 'Tlatlaya'),
('MIC', 'Vista Hermosa'),
('OAX', 'San Antonino Monte Verde'),
('PUE', 'Ocotepec'),
('VER', 'Medellín'),
('YUC', 'Yaxkukul'),
('CHP', 'Venustiano Carranza'),
('JAL', 'Tuxcacuesco'),
('MEX', 'Toluca'),
('MIC', 'Yurécuaro'),
('OAX', 'San Antonio Acutla'),
('PUE', 'Ocoyucan'),
('VER', 'Miahuatlán'),
('YUC', 'Yobaín'),
('CHP', 'Villa Corzo'),
('JAL', 'Tuxcueca'),
('MEX', 'Tonatico'),
('MIC', 'Zacapu'),
('OAX', 'San Antonio de la Cal'),
('PUE', 'Olintla'),
('VER', 'Las Minas'),
('CHP', 'Villaflores'),
('JAL', 'Tuxpan'),
('MEX', 'Tultepec'),
('MIC', 'Zamora'),
('OAX', 'San Antonio Huitepec'),
('PUE', 'Oriental'),
('VER', 'Minatitlán'),
('CHP', 'Yajalón'),
('JAL', 'Unión de San Antonio'),
('MEX', 'Tultitlán'),
('MIC', 'Zináparo'),
('OAX', 'San Antonio Nanahuatípam'),
('PUE', 'Pahuatlán'),
('VER', 'Misantla'),
('CHP', 'San Lucas'),
('JAL', 'Unión de Tula'),
('MEX', 'Valle de Bravo'),
('MIC', 'Zinapécuaro'),
('OAX', 'San Antonio Sinicahua'),
('PUE', 'Palmar de Bravo'),
('VER', 'Mixtla de Altamirano'),
('CHP', 'Zinacantán'),
('JAL', 'Valle de Guadalupe'),
('MEX', 'Villa de Allende'),
('MIC', 'Ziracuaretiro'),
('OAX', 'San Antonio Tepetlapa'),
('PUE', 'Pantepec'),
('VER', 'Moloacán'),
('CHP', 'San Juan Cancuc'),
('JAL', 'Valle de Juárez'),
('MEX', 'Villa del Carbón'),
('MIC', 'Zitácuaro'),
('OAX', 'San Baltazar Chichicápam'),
('PUE', 'Petlalcingo'),
('VER', 'Naolinco'),
('CHP', 'Aldama'),
('JAL', 'San Gabriel'),
('MEX', 'Villa Guerrero'),
('MIC', 'José Sixto Verduzco'),
('OAX', 'San Baltazar Loxicha'),
('PUE', 'Piaxtla'),
('VER', 'Naranjal'),
('CHP', 'Benemérito de las Américas'),
('JAL', 'Villa Corona'),
('MEX', 'Villa Victoria'),
('OAX', 'San Baltazar Yatzachi el Bajo'),
('PUE', 'Puebla'),
('VER', 'Nautla'),
('CHP', 'Maravilla Tenejapa'),
('JAL', 'Villa Guerrero'),
('MEX', 'Xonacatlán'),
('OAX', 'San Bartolo Coyotepec'),
('PUE', 'Quecholac'),
('VER', 'Nogales'),
('CHP', 'Marqués de Comillas'),
('JAL', 'Villa Hidalgo'),
('MEX', 'Zacazonapan'),
('OAX', 'San Bartolomé Ayautla'),
('PUE', 'Quimixtlán'),
('VER', 'Oluta'),
('CHP', 'Montecristo de Guerrero'),
('JAL', 'Cañadas de Obregón'),
('MEX', 'Zacualpan'),
('OAX', 'San Bartolomé Loxicha'),
('PUE', 'Rafael Lara Grajales'),
('VER', 'Omealca'),
('CHP', 'San Andrés Duraznal'),
('JAL', 'Yahualica de González Gallo'),
('MEX', 'Zinacantepec'),
('OAX', 'San Bartolomé Quialana'),
('PUE', 'Los Reyes de Juárez'),
('VER', 'Orizaba'),
('CHP', 'Santiago el Pinar'),
('JAL', 'Zacoalco de Torres'),
('MEX', 'Zumpahuacán'),
('OAX', 'San Bartolomé Yucuañe'),
('PUE', 'San Andrés Cholula'),
('VER', 'Otatitlán'),
('JAL', 'Zapopan'),
('MEX', 'Zumpango'),
('OAX', 'San Bartolomé Zoogocho'),
('PUE', 'San Antonio Cañada'),
('VER', 'Oteapan'),
('CHP', 'Capitán Luis Ángel Vidal'),
('JAL', 'Zapotiltic'),
('MEX', 'Cuautitlán Izcalli'),
('OAX', 'San Bartolo Soyaltepec'),
('PUE', 'San Diego la Mesa Tochimiltzingo'),
('VER', 'Ozuluama de Mascareñas'),
('CHP', 'Rincón Chamula San Pedro'),
('JAL', 'Zapotitlán de Vadillo'),
('MEX', 'Valle de Chalco Solidaridad'),
('OAX', 'San Bartolo Yautepec'),
('PUE', 'San Felipe Teotlalcingo'),
('VER', 'Pajapan'),
('CHP', 'El Parral'),
('JAL', 'Zapotlán del Rey'),
('MEX', 'Luvianos'),
('OAX', 'San Bernardo Mixtepec'),
('PUE', 'San Felipe Tepatlán'),
('VER', 'Pánuco'),
('CHP', 'Emiliano Zapata'),
('JAL', 'Zapotlanejo'),
('MEX', 'San José del Rincón'),
('OAX', 'San Blas Atempa'),
('PUE', 'San Gabriel Chilac'),
('VER', 'Papantla'),
('CHP', 'Mezcalapa'),
('JAL', 'San Ignacio Cerro Gordo'),
('MEX', 'Tonanitla'),
('OAX', 'San Carlos Yautepec'),
('PUE', 'San Gregorio Atzompa'),
('VER', 'Paso del Macho'),
('OAX', 'San Cristóbal Amatlán'),
('PUE', 'San Jerónimo Tecuanipan'),
('VER', 'Paso de Ovejas'),
('OAX', 'San Cristóbal Amoltepec'),
('PUE', 'San Jerónimo Xayacatlán'),
('VER', 'La Perla'),
('OAX', 'San Cristóbal Lachirioag'),
('PUE', 'San José Chiapa'),
('VER', 'Perote'),
('OAX', 'San Cristóbal Suchixtlahuaca'),
('PUE', 'San José Miahuatlán'),
('VER', 'Platón Sánchez'),
('OAX', 'San Dionisio del Mar'),
('PUE', 'San Juan Atenco'),
('VER', 'Playa Vicente'),
('OAX', 'San Dionisio Ocotepec'),
('PUE', 'San Juan Atzompa'),
('VER', 'Poza Rica de Hidalgo'),
('OAX', 'San Dionisio Ocotlán'),
('PUE', 'San Martín Texmelucan'),
('VER', 'Las Vigas de Ramírez'),
('OAX', 'San Esteban Atatlahuca'),
('PUE', 'San Martín Totoltepec'),
('VER', 'Pueblo Viejo'),
('OAX', 'San Felipe Jalapa de Díaz'),
('PUE', 'San Matías Tlalancaleca'),
('VER', 'Puente Nacional'),
('OAX', 'San Felipe Tejalápam'),
('PUE', 'San Miguel Ixitlán'),
('VER', 'Rafael Delgado'),
('OAX', 'San Felipe Usila'),
('PUE', 'San Miguel Xoxtla'),
('VER', 'Rafael Lucio'),
('OAX', 'San Francisco Cahuacuá'),
('PUE', 'San Nicolás Buenos Aires'),
('VER', 'Los Reyes'),
('OAX', 'San Francisco Cajonos'),
('PUE', 'San Nicolás de los Ranchos'),
('VER', 'Río Blanco'),
('OAX', 'San Francisco Chapulapa'),
('PUE', 'San Pablo Anicano'),
('VER', 'Saltabarranca'),
('OAX', 'San Francisco Chindúa'),
('PUE', 'San Pedro Cholula'),
('VER', 'San Andrés Tenejapan'),
('OAX', 'San Francisco del Mar'),
('PUE', 'San Pedro Yeloixtlahuaca'),
('VER', 'San Andrés Tuxtla'),
('OAX', 'San Francisco Huehuetlán'),
('PUE', 'San Salvador el Seco'),
('VER', 'San Juan Evangelista'),
('OAX', 'San Francisco Ixhuatán'),
('PUE', 'San Salvador el Verde'),
('VER', 'Santiago Tuxtla'),
('OAX', 'San Francisco Jaltepetongo'),
('PUE', 'San Salvador Huixcolotla'),
('VER', 'Sayula de Alemán'),
('OAX', 'San Francisco Lachigoló'),
('PUE', 'San Sebastián Tlacotepec'),
('VER', 'Soconusco'),
('OAX', 'San Francisco Logueche'),
('PUE', 'Santa Catarina Tlaltempan'),
('VER', 'Sochiapa'),
('OAX', 'San Francisco Nuxaño'),
('PUE', 'Santa Inés Ahuatempan'),
('VER', 'Soledad Atzompa'),
('OAX', 'San Francisco Ozolotepec'),
('PUE', 'Santa Isabel Cholula'),
('VER', 'Soledad de Doblado'),
('OAX', 'San Francisco Sola'),
('PUE', 'Santiago Miahuatlán'),
('VER', 'Soteapan'),
('OAX', 'San Francisco Telixtlahuaca'),
('PUE', 'Huehuetlán el Grande'),
('VER', 'Tamalín'),
('OAX', 'San Francisco Teopan'),
('PUE', 'Santo Tomás Hueyotlipan'),
('VER', 'Tamiahua'),
('OAX', 'San Francisco Tlapancingo'),
('PUE', 'Soltepec'),
('VER', 'Tampico Alto'),
('OAX', 'San Gabriel Mixtepec'),
('PUE', 'Tecali de Herrera'),
('VER', 'Tancoco'),
('OAX', 'San Ildefonso Amatlán'),
('PUE', 'Tecamachalco'),
('VER', 'Tantima'),
('OAX', 'San Ildefonso Sola'),
('PUE', 'Tecomatlán'),
('VER', 'Tantoyuca'),
('OAX', 'San Ildefonso Villa Alta'),
('PUE', 'Tehuacán'),
('VER', 'Tatatila'),
('OAX', 'San Jacinto Amilpas'),
('PUE', 'Tehuitzingo'),
('VER', 'Castillo de Teayo'),
('OAX', 'San Jacinto Tlacotepec'),
('PUE', 'Tenampulco'),
('VER', 'Tecolutla'),
('OAX', 'San Jerónimo Coatlán'),
('PUE', 'Teopantlán'),
('VER', 'Tehuipango'),
('OAX', 'San Jerónimo Silacayoapilla'),
('PUE', 'Teotlalco'),
('VER', 'Álamo Temapache'),
('OAX', 'San Jerónimo Sosola'),
('PUE', 'Tepanco de López'),
('VER', 'Tempoal'),
('OAX', 'San Jerónimo Taviche'),
('PUE', 'Tepango de Rodríguez'),
('VER', 'Tenampa'),
('OAX', 'San Jerónimo Tecóatl'),
('PUE', 'Tepatlaxco de Hidalgo'),
('VER', 'Tenochtitlán'),
('OAX', 'San Jorge Nuchita'),
('PUE', 'Tepeaca'),
('VER', 'Teocelo'),
('OAX', 'San José Ayuquila'),
('PUE', 'Tepemaxalco'),
('VER', 'Tepatlaxco'),
('OAX', 'San José Chiltepec'),
('PUE', 'Tepeojuma'),
('VER', 'Tepetlán'),
('OAX', 'San José del Peñasco'),
('PUE', 'Tepetzintla'),
('VER', 'Tepetzintla'),
('OAX', 'San José Estancia Grande'),
('PUE', 'Tepexco'),
('VER', 'Tequila'),
('OAX', 'San José Independencia'),
('PUE', 'Tepexi de Rodríguez'),
('VER', 'José Azueta'),
('OAX', 'San José Lachiguiri'),
('PUE', 'Tepeyahualco'),
('VER', 'Texcatepec'),
('OAX', 'San José Tenango'),
('PUE', 'Tepeyahualco de Cuauhtémoc'),
('VER', 'Texhuacán'),
('OAX', 'San Juan Achiutla'),
('PUE', 'Tetela de Ocampo'),
('VER', 'Texistepec'),
('OAX', 'San Juan Atepec'),
('PUE', 'Teteles de Avila Castillo'),
('VER', 'Tezonapa'),
('OAX', 'Ánimas Trujano'),
('PUE', 'Teziutlán'),
('VER', 'Tierra Blanca'),
('OAX', 'San Juan Bautista Atatlahuca'),
('PUE', 'Tianguismanalco'),
('VER', 'Tihuatlán'),
('OAX', 'San Juan Bautista Coixtlahuaca'),
('PUE', 'Tilapa'),
('VER', 'Tlacojalpan'),
('OAX', 'San Juan Bautista Cuicatlán'),
('PUE', 'Tlacotepec de Benito Juárez'),
('VER', 'Tlacolulan'),
('OAX', 'San Juan Bautista Guelache'),
('PUE', 'Tlacuilotepec'),
('VER', 'Tlacotalpan'),
('OAX', 'San Juan Bautista Jayacatlán'),
('PUE', 'Tlachichuca'),
('VER', 'Tlacotepec de Mejía'),
('OAX', 'San Juan Bautista Lo de Soto'),
('PUE', 'Tlahuapan'),
('VER', 'Tlachichilco'),
('OAX', 'San Juan Bautista Suchitepec'),
('PUE', 'Tlaltenango'),
('VER', 'Tlalixcoyan'),
('OAX', 'San Juan Bautista Tlacoatzintepec'),
('PUE', 'Tlanepantla'),
('VER', 'Tlalnelhuayocan'),
('OAX', 'San Juan Bautista Tlachichilco'),
('PUE', 'Tlaola'),
('VER', 'Tlapacoyan'),
('OAX', 'San Juan Bautista Tuxtepec'),
('PUE', 'Tlapacoya'),
('VER', 'Tlaquilpa'),
('OAX', 'San Juan Cacahuatepec'),
('PUE', 'Tlapanalá'),
('VER', 'Tlilapan'),
('OAX', 'San Juan Cieneguilla'),
('PUE', 'Tlatlauquitepec'),
('VER', 'Tomatlán'),
('OAX', 'San Juan Coatzóspam'),
('PUE', 'Tlaxco'),
('VER', 'Tonayán'),
('OAX', 'San Juan Colorado'),
('PUE', 'Tochimilco'),
('VER', 'Totutla'),
('OAX', 'San Juan Comaltepec'),
('PUE', 'Tochtepec'),
('VER', 'Tuxpan'),
('OAX', 'San Juan Cotzocón'),
('PUE', 'Totoltepec de Guerrero'),
('VER', 'Tuxtilla'),
('OAX', 'San Juan Chicomezúchil'),
('PUE', 'Tulcingo'),
('VER', 'Ursulo Galván'),
('OAX', 'San Juan Chilateca'),
('PUE', 'Tuzamapan de Galeana'),
('VER', 'Vega de Alatorre'),
('OAX', 'San Juan del Estado'),
('PUE', 'Tzicatlacoyan'),
('VER', 'Veracruz'),
('OAX', 'San Juan del Río'),
('PUE', 'Venustiano Carranza'),
('VER', 'Villa Aldama'),
('OAX', 'San Juan Diuxi'),
('PUE', 'Vicente Guerrero'),
('VER', 'Xoxocotla'),
('OAX', 'San Juan Evangelista Analco'),
('PUE', 'Xayacatlán de Bravo'),
('VER', 'Yanga'),
('OAX', 'San Juan Guelavía'),
('PUE', 'Xicotepec'),
('VER', 'Yecuatla'),
('OAX', 'San Juan Guichicovi'),
('PUE', 'Xicotlán'),
('VER', 'Zacualpan'),
('OAX', 'San Juan Ihualtepec'),
('PUE', 'Xiutetelco'),
('VER', 'Zaragoza'),
('OAX', 'San Juan Juquila Mixes'),
('PUE', 'Xochiapulco'),
('VER', 'Zentla'),
('OAX', 'San Juan Juquila Vijanos'),
('PUE', 'Xochiltepec'),
('VER', 'Zongolica'),
('OAX', 'San Juan Lachao'),
('PUE', 'Xochitlán de Vicente Suárez'),
('VER', 'Zontecomatlán de López y Fuentes'),
('OAX', 'San Juan Lachigalla'),
('PUE', 'Xochitlán Todos Santos'),
('VER', 'Zozocolco de Hidalgo'),
('OAX', 'San Juan Lajarcia'),
('PUE', 'Yaonáhuac'),
('VER', 'Agua Dulce'),
('OAX', 'San Juan Lalana'),
('PUE', 'Yehualtepec'),
('VER', 'El Higo'),
('OAX', 'San Juan de los Cués'),
('PUE', 'Zacapala'),
('VER', 'Nanchital de Lázaro Cárdenas del Río'),
('OAX', 'San Juan Mazatlán'),
('PUE', 'Zacapoaxtla'),
('VER', 'Tres Valles'),
('OAX', 'San Juan Mixtepec -Dto. 08 -'),
('PUE', 'Zacatlán'),
('VER', 'Carlos A. Carrillo'),
('OAX', 'San Juan Mixtepec -Dto. 26 -'),
('PUE', 'Zapotitlán'),
('VER', 'Tatahuicapan de Juárez'),
('OAX', 'San Juan Ñumí'),
('PUE', 'Zapotitlán de Méndez'),
('VER', 'Uxpanapa'),
('OAX', 'San Juan Ozolotepec'),
('PUE', 'Zaragoza'),
('VER', 'San Rafael'),
('OAX', 'San Juan Petlapa'),
('PUE', 'Zautla'),
('VER', 'Santiago Sochiapan'),
('OAX', 'San Juan Quiahije'),
('PUE', 'Zihuateutla'),
('OAX', 'San Juan Quiotepec'),
('PUE', 'Zinacatepec'),
('OAX', 'San Juan Sayultepec'),
('PUE', 'Zongozotla'),
('OAX', 'San Juan Tabaá'),
('PUE', 'Zoquiapan'),
('OAX', 'San Juan Tamazola'),
('PUE', 'Zoquitlán'),
('OAX', 'San Juan Teita'),
('OAX', 'San Juan Teitipac'),
('OAX', 'San Juan Tepeuxila'),
('OAX', 'San Juan Teposcolula'),
('OAX', 'San Juan Yaeé'),
('OAX', 'San Juan Yatzona'),
('OAX', 'San Juan Yucuita'),
('OAX', 'San Lorenzo'),
('OAX', 'San Lorenzo Albarradas'),
('OAX', 'San Lorenzo Cacaotepec'),
('OAX', 'San Lorenzo Cuaunecuiltitla'),
('OAX', 'San Lorenzo Texmelúcan'),
('OAX', 'San Lorenzo Victoria'),
('OAX', 'San Lucas Camotlán'),
('OAX', 'San Lucas Ojitlán'),
('OAX', 'San Lucas Quiaviní'),
('OAX', 'San Lucas Zoquiápam'),
('OAX', 'San Luis Amatlán'),
('OAX', 'San Marcial Ozolotepec'),
('OAX', 'San Marcos Arteaga'),
('OAX', 'San Martín de los Cansecos'),
('OAX', 'San Martín Huamelúlpam'),
('OAX', 'San Martín Itunyoso'),
('OAX', 'San Martín Lachilá'),
('OAX', 'San Martín Peras'),
('OAX', 'San Martín Tilcajete'),
('OAX', 'San Martín Toxpalan'),
('OAX', 'San Martín Zacatepec'),
('OAX', 'San Mateo Cajonos'),
('OAX', 'Capulálpam de Méndez'),
('OAX', 'San Mateo del Mar'),
('OAX', 'San Mateo Yoloxochitlán'),
('OAX', 'San Mateo Etlatongo'),
('OAX', 'San Mateo Nejápam'),
('OAX', 'San Mateo Peñasco'),
('OAX', 'San Mateo Piñas'),
('OAX', 'San Mateo Río Hondo'),
('OAX', 'San Mateo Sindihui'),
('OAX', 'San Mateo Tlapiltepec'),
('OAX', 'San Melchor Betaza'),
('OAX', 'San Miguel Achiutla'),
('OAX', 'San Miguel Ahuehuetitlán'),
('OAX', 'San Miguel Aloápam'),
('OAX', 'San Miguel Amatitlán'),
('OAX', 'San Miguel Amatlán'),
('OAX', 'San Miguel Coatlán'),
('OAX', 'San Miguel Chicahua'),
('OAX', 'San Miguel Chimalapa'),
('OAX', 'San Miguel del Puerto'),
('OAX', 'San Miguel del Río'),
('OAX', 'San Miguel Ejutla'),
('OAX', 'San Miguel el Grande'),
('OAX', 'San Miguel Huautla'),
('OAX', 'San Miguel Mixtepec'),
('OAX', 'San Miguel Panixtlahuaca'),
('OAX', 'San Miguel Peras'),
('OAX', 'San Miguel Piedras'),
('OAX', 'San Miguel Quetzaltepec'),
('OAX', 'San Miguel Santa Flor'),
('OAX', 'Villa Sola de Vega'),
('OAX', 'San Miguel Soyaltepec'),
('OAX', 'San Miguel Suchixtepec'),
('OAX', 'Villa Talea de Castro'),
('OAX', 'San Miguel Tecomatlán'),
('OAX', 'San Miguel Tenango'),
('OAX', 'San Miguel Tequixtepec'),
('OAX', 'San Miguel Tilquiápam'),
('OAX', 'San Miguel Tlacamama'),
('OAX', 'San Miguel Tlacotepec'),
('OAX', 'San Miguel Tulancingo'),
('OAX', 'San Miguel Yotao'),
('OAX', 'San Nicolás'),
('OAX', 'San Nicolás Hidalgo'),
('OAX', 'San Pablo Coatlán'),
('OAX', 'San Pablo Cuatro Venados'),
('OAX', 'San Pablo Etla'),
('OAX', 'San Pablo Huitzo'),
('OAX', 'San Pablo Huixtepec'),
('OAX', 'San Pablo Macuiltianguis'),
('OAX', 'San Pablo Tijaltepec'),
('OAX', 'San Pablo Villa de Mitla'),
('OAX', 'San Pablo Yaganiza'),
('OAX', 'San Pedro Amuzgos'),
('OAX', 'San Pedro Apóstol'),
('OAX', 'San Pedro Atoyac'),
('OAX', 'San Pedro Cajonos'),
('OAX', 'San Pedro Coxcaltepec Cántaros'),
('OAX', 'San Pedro Comitancillo'),
('OAX', 'San Pedro el Alto'),
('OAX', 'San Pedro Huamelula'),
('OAX', 'San Pedro Huilotepec'),
('OAX', 'San Pedro Ixcatlán'),
('OAX', 'San Pedro Ixtlahuaca'),
('OAX', 'San Pedro Jaltepetongo'),
('OAX', 'San Pedro Jicayán'),
('OAX', 'San Pedro Jocotipac'),
('OAX', 'San Pedro Juchatengo'),
('OAX', 'San Pedro Mártir'),
('OAX', 'San Pedro Mártir Quiechapa'),
('OAX', 'San Pedro Mártir Yucuxaco'),
('OAX', 'San Pedro Mixtepec -Dto. 22 -'),
('OAX', 'San Pedro Mixtepec -Dto. 26 -'),
('OAX', 'San Pedro Molinos'),
('OAX', 'San Pedro Nopala'),
('OAX', 'San Pedro Ocopetatillo'),
('OAX', 'San Pedro Ocotepec'),
('OAX', 'San Pedro Pochutla'),
('OAX', 'San Pedro Quiatoni'),
('OAX', 'San Pedro Sochiápam'),
('OAX', 'San Pedro Tapanatepec'),
('OAX', 'San Pedro Taviche'),
('OAX', 'San Pedro Teozacoalco'),
('OAX', 'San Pedro Teutila'),
('OAX', 'San Pedro Tidaá'),
('OAX', 'San Pedro Topiltepec'),
('OAX', 'San Pedro Totolápam'),
('OAX', 'Villa de Tututepec de Melchor Ocampo'),
('OAX', 'San Pedro Yaneri'),
('OAX', 'San Pedro Yólox'),
('OAX', 'San Pedro y San Pablo Ayutla'),
('OAX', 'Villa de Etla'),
('OAX', 'San Pedro y San Pablo Teposcolula'),
('OAX', 'San Pedro y San Pablo Tequixtepec'),
('OAX', 'San Pedro Yucunama'),
('OAX', 'San Raymundo Jalpan'),
('OAX', 'San Sebastián Abasolo'),
('OAX', 'San Sebastián Coatlán'),
('OAX', 'San Sebastián Ixcapa'),
('OAX', 'San Sebastián Nicananduta'),
('OAX', 'San Sebastián Río Hondo'),
('OAX', 'San Sebastián Tecomaxtlahuaca'),
('OAX', 'San Sebastián Teitipac'),
('OAX', 'San Sebastián Tutla'),
('OAX', 'San Simón Almolongas'),
('OAX', 'San Simón Zahuatlán'),
('OAX', 'Santa Ana'),
('OAX', 'Santa Ana Ateixtlahuaca'),
('OAX', 'Santa Ana Cuauhtémoc'),
('OAX', 'Santa Ana del Valle'),
('OAX', 'Santa Ana Tavela'),
('OAX', 'Santa Ana Tlapacoyan'),
('OAX', 'Santa Ana Yareni'),
('OAX', 'Santa Ana Zegache'),
('OAX', 'Santa Catalina Quierí'),
('OAX', 'Santa Catarina Cuixtla'),
('OAX', 'Santa Catarina Ixtepeji'),
('OAX', 'Santa Catarina Juquila'),
('OAX', 'Santa Catarina Lachatao'),
('OAX', 'Santa Catarina Loxicha'),
('OAX', 'Santa Catarina Mechoacán'),
('OAX', 'Santa Catarina Minas'),
('OAX', 'Santa Catarina Quiané'),
('OAX', 'Santa Catarina Tayata'),
('OAX', 'Santa Catarina Ticuá'),
('OAX', 'Santa Catarina Yosonotú'),
('OAX', 'Santa Catarina Zapoquila'),
('OAX', 'Santa Cruz Acatepec'),
('OAX', 'Santa Cruz Amilpas'),
('OAX', 'Santa Cruz de Bravo'),
('OAX', 'Santa Cruz Itundujia'),
('OAX', 'Santa Cruz Mixtepec'),
('OAX', 'Santa Cruz Nundaco'),
('OAX', 'Santa Cruz Papalutla'),
('OAX', 'Santa Cruz Tacache de Mina'),
('OAX', 'Santa Cruz Tacahua'),
('OAX', 'Santa Cruz Tayata'),
('OAX', 'Santa Cruz Xitla'),
('OAX', 'Santa Cruz Xoxocotlán'),
('OAX', 'Santa Cruz Zenzontepec'),
('OAX', 'Santa Gertrudis'),
('OAX', 'Santa Inés del Monte'),
('OAX', 'Santa Inés Yatzeche'),
('OAX', 'Santa Lucía del Camino'),
('OAX', 'Santa Lucía Miahuatlán'),
('OAX', 'Santa Lucía Monteverde'),
('OAX', 'Santa Lucía Ocotlán'),
('OAX', 'Santa María Alotepec'),
('OAX', 'Santa María Apazco'),
('OAX', 'Santa María la Asunción'),
('OAX', 'Heroica Ciudad de Tlaxiaco'),
('OAX', 'Ayoquezco de Aldama'),
('OAX', 'Santa María Atzompa'),
('OAX', 'Santa María Camotlán'),
('OAX', 'Santa María Colotepec'),
('OAX', 'Santa María Cortijo'),
('OAX', 'Santa María Coyotepec'),
('OAX', 'Santa María Chachoápam'),
('OAX', 'Villa de Chilapa de Díaz'),
('OAX', 'Santa María Chilchotla'),
('OAX', 'Santa María Chimalapa'),
('OAX', 'Santa María del Rosario'),
('OAX', 'Santa María del Tule'),
('OAX', 'Santa María Ecatepec'),
('OAX', 'Santa María Guelacé'),
('OAX', 'Santa María Guienagati'),
('OAX', 'Santa María Huatulco'),
('OAX', 'Santa María Huazolotitlán'),
('OAX', 'Santa María Ipalapa'),
('OAX', 'Santa María Ixcatlán'),
('OAX', 'Santa María Jacatepec'),
('OAX', 'Santa María Jalapa del Marqués'),
('OAX', 'Santa María Jaltianguis'),
('OAX', 'Santa María Lachixío'),
('OAX', 'Santa María Mixtequilla'),
('OAX', 'Santa María Nativitas'),
('OAX', 'Santa María Nduayaco'),
('OAX', 'Santa María Ozolotepec'),
('OAX', 'Santa María Pápalo'),
('OAX', 'Santa María Peñoles'),
('OAX', 'Santa María Petapa'),
('OAX', 'Santa María Quiegolani'),
('OAX', 'Santa María Sola'),
('OAX', 'Santa María Tataltepec'),
('OAX', 'Santa María Tecomavaca'),
('OAX', 'Santa María Temaxcalapa'),
('OAX', 'Santa María Temaxcaltepec'),
('OAX', 'Santa María Teopoxco'),
('OAX', 'Santa María Tepantlali'),
('OAX', 'Santa María Texcatitlán'),
('OAX', 'Santa María Tlahuitoltepec'),
('OAX', 'Santa María Tlalixtac'),
('OAX', 'Santa María Tonameca'),
('OAX', 'Santa María Totolapilla'),
('OAX', 'Santa María Xadani'),
('OAX', 'Santa María Yalina'),
('OAX', 'Santa María Yavesía'),
('OAX', 'Santa María Yolotepec'),
('OAX', 'Santa María Yosoyúa'),
('OAX', 'Santa María Yucuhiti'),
('OAX', 'Santa María Zacatepec'),
('OAX', 'Santa María Zaniza'),
('OAX', 'Santa María Zoquitlán'),
('OAX', 'Santiago Amoltepec'),
('OAX', 'Santiago Apoala'),
('OAX', 'Santiago Apóstol'),
('OAX', 'Santiago Astata'),
('OAX', 'Santiago Atitlán'),
('OAX', 'Santiago Ayuquililla'),
('OAX', 'Santiago Cacaloxtepec'),
('OAX', 'Santiago Camotlán'),
('OAX', 'Santiago Comaltepec'),
('OAX', 'Santiago Chazumba'),
('OAX', 'Santiago Choápam'),
('OAX', 'Santiago del Río'),
('OAX', 'Santiago Huajolotitlán'),
('OAX', 'Santiago Huauclilla'),
('OAX', 'Santiago Ihuitlán Plumas'),
('OAX', 'Santiago Ixcuintepec'),
('OAX', 'Santiago Ixtayutla'),
('OAX', 'Santiago Jamiltepec'),
('OAX', 'Santiago Jocotepec'),
('OAX', 'Santiago Juxtlahuaca'),
('OAX', 'Santiago Lachiguiri'),
('OAX', 'Santiago Lalopa'),
('OAX', 'Santiago Laollaga'),
('OAX', 'Santiago Laxopa'),
('OAX', 'Santiago Llano Grande'),
('OAX', 'Santiago Matatlán'),
('OAX', 'Santiago Miltepec'),
('OAX', 'Santiago Minas'),
('OAX', 'Santiago Nacaltepec'),
('OAX', 'Santiago Nejapilla'),
('OAX', 'Santiago Nundiche'),
('OAX', 'Santiago Nuyoó'),
('OAX', 'Santiago Pinotepa Nacional'),
('OAX', 'Santiago Suchilquitongo'),
('OAX', 'Santiago Tamazola'),
('OAX', 'Santiago Tapextla'),
('OAX', 'Villa Tejúpam de la Unión'),
('OAX', 'Santiago Tenango'),
('OAX', 'Santiago Tepetlapa'),
('OAX', 'Santiago Tetepec'),
('OAX', 'Santiago Texcalcingo'),
('OAX', 'Santiago Textitlán'),
('OAX', 'Santiago Tilantongo'),
('OAX', 'Santiago Tillo'),
('OAX', 'Santiago Tlazoyaltepec'),
('OAX', 'Santiago Xanica'),
('OAX', 'Santiago Xiacuí'),
('OAX', 'Santiago Yaitepec'),
('OAX', 'Santiago Yaveo'),
('OAX', 'Santiago Yolomécatl'),
('OAX', 'Santiago Yosondúa'),
('OAX', 'Santiago Yucuyachi'),
('OAX', 'Santiago Zacatepec'),
('OAX', 'Santiago Zoochila'),
('OAX', 'Nuevo Zoquiápam'),
('OAX', 'Santo Domingo Ingenio'),
('OAX', 'Santo Domingo Albarradas'),
('OAX', 'Santo Domingo Armenta'),
('OAX', 'Santo Domingo Chihuitán'),
('OAX', 'Santo Domingo de Morelos'),
('OAX', 'Santo Domingo Ixcatlán'),
('OAX', 'Santo Domingo Nuxaá'),
('OAX', 'Santo Domingo Ozolotepec'),
('OAX', 'Santo Domingo Petapa'),
('OAX', 'Santo Domingo Roayaga'),
('OAX', 'Santo Domingo Tehuantepec'),
('OAX', 'Santo Domingo Teojomulco'),
('OAX', 'Santo Domingo Tepuxtepec'),
('OAX', 'Santo Domingo Tlatayápam'),
('OAX', 'Santo Domingo Tomaltepec'),
('OAX', 'Santo Domingo Tonalá'),
('OAX', 'Santo Domingo Tonaltepec'),
('OAX', 'Santo Domingo Xagacía'),
('OAX', 'Santo Domingo Yanhuitlán'),
('OAX', 'Santo Domingo Yodohino'),
('OAX', 'Santo Domingo Zanatepec'),
('OAX', 'Santos Reyes Nopala'),
('OAX', 'Santos Reyes Pápalo'),
('OAX', 'Santos Reyes Tepejillo'),
('OAX', 'Santos Reyes Yucuná'),
('OAX', 'Santo Tomás Jalieza'),
('OAX', 'Santo Tomás Mazaltepec'),
('OAX', 'Santo Tomás Ocotepec'),
('OAX', 'Santo Tomás Tamazulapan'),
('OAX', 'San Vicente Coatlán'),
('OAX', 'San Vicente Lachixío'),
('OAX', 'San Vicente Nuñú'),
('OAX', 'Silacayoápam'),
('OAX', 'Sitio de Xitlapehua'),
('OAX', 'Soledad Etla'),
('OAX', 'Villa de Tamazulápam del Progreso'),
('OAX', 'Tanetze de Zaragoza'),
('OAX', 'Taniche'),
('OAX', 'Tataltepec de Valdés'),
('OAX', 'Teococuilco de Marcos Pérez'),
('OAX', 'Teotitlán de Flores Magón'),
('OAX', 'Teotitlán del Valle'),
('OAX', 'Teotongo'),
('OAX', 'Tepelmeme Villa de Morelos'),
('OAX', 'Tezoatlán de Segura y Luna'),
('OAX', 'San Jerónimo Tlacochahuaya'),
('OAX', 'Tlacolula de Matamoros'),
('OAX', 'Tlacotepec Plumas'),
('OAX', 'Tlalixtac de Cabrera'),
('OAX', 'Totontepec Villa de Morelos'),
('OAX', 'Trinidad Zaachila'),
('OAX', 'La Trinidad Vista Hermosa'),
('OAX', 'Unión Hidalgo'),
('OAX', 'Valerio Trujano'),
('OAX', 'San Juan Bautista Valle Nacional'),
('OAX', 'Villa Díaz Ordaz'),
('OAX', 'Yaxe'),
('OAX', 'Magdalena Yodocono de Porfirio Díaz'),
('OAX', 'Yogana'),
('OAX', 'Yutanduchi de Guerrero'),
('OAX', 'Villa de Zaachila'),
('OAX', 'San Mateo Yucutindoo'),
('OAX', 'Zapotitlán Lagunas'),
('OAX', 'Zapotitlán Palmas'),
('OAX', 'Santa Inés de Zaragoza'),
('OAX', 'Zimatlán de Álvarez');